/**
 * Import suppliers S0312–S0333 + UPDATE S0334
 * node scripts/import_suppliers_s312_s333.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0333',
    sup_type: 'company',
    sup_name: 'บริษัท แอดวานซ์ ไวเลส เน็ทเวอร์ค จำกัด (Pocket Wifi)',
    tax_id: '0105548115897',
    branch_type: 'HO',
    address_line1: 'เลขที่ 414 ถนนพหลโยธิน',
    sub_district: 'สามเสนใน',
    district: 'พญาไท',
    province: 'กรุงเทพมหานคร',
    postal_code: '10400',
    contact_name: 'T.1175',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    partner_type: 'อินเตอร์เน็ต',
  },
  {
    sup_code: 'S0332',
    sup_type: 'company',
    sup_name: 'บริษัท โรเอ่น กรุ๊ป อินเตอร์เนชั่นแนล(ประเทศไทย) จำกัด',
    tax_id: '0105558130163',
    branch_type: 'HO',
    address_line1: '18/1-18/2 ซอยหทัยราษฎร์ 32',
    sub_district: 'สามวาตะวันตก',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_name: 'คุณปอ',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0331',
    sup_type: 'individual',
    sup_name: 'บริษัท จ้าวเหนือ คอฟฟี่ จำกัด',
    branch_type: '-',
    contact_name: 'คุณเล็ก',
    contact_phone: '082-6535966',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0330',
    sup_type: 'individual',
    sup_name: 'คุณพัชรา เนียมซุยขิน',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0329',
    sup_type: 'company',
    sup_name: 'บริษัท บลูสปอร์ต จำกัด',
    branch_type: 'HO',
    address_line1: '169/48-49 ถนนประดิษัทธ์',
    district: 'พญาไท',
    province: 'กรุงเทพมหานคร',
    postal_code: '10400',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0328',
    sup_type: 'individual',
    sup_name: 'คุณสุวัฒน์ เกษมสุขสถาพร',
    branch_type: '-',
    contact_name: 'คุณสุวัฒน์',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0327',
    sup_type: 'individual',
    sup_name: 'คุณวิชุดา บางเมือง',
    branch_type: '-',
    address_line1: '109/138 หมู่บ้านซันซิตี้ไพร์ม พาร์ค ซอย10',
    sub_district: 'ท่าแร้ง',
    district: 'บางเขน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10220',
    contact_name: 'คุณปอย',
    contact_phone: '087-5956393',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0326',
    sup_type: 'company',
    sup_name: 'บริษัท แสงทองผ้าใบ กันสาด จำกัด',
    tax_id: '0105540015095',
    branch_type: 'HO',
    address_line1: '449 ถนนประดิษัทธ์มนูธรรม',
    sub_district: 'วังทองหลาง',
    district: 'วังทองหลาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'คุณสมบูรณ์',
    contact_phone: '089-1234114',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0325',
    sup_type: 'individual',
    sup_name: 'นาย ปุณณวิช นพคุณ',
    tax_id: '1102700671349',
    branch_type: '-',
    address_line1: '21 ซอยสุวินทวงค์13 แยก8',
    sub_district: 'แสนแสบ',
    district: 'มีนบุรี',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_name: 'คุณพิเจ',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว',
  },
  {
    sup_code: 'S0324',
    sup_type: 'company',
    sup_name: 'เพอร์เฟค-เดคคอร์',
    branch_type: 'HO',
    address_line1: 'JJ Mall G236 ชั้นใต้ดิน โซนC 588 ถนนกำแพงเพชร 2',
    sub_district: 'จตุจักร',
    district: 'จตุจักร',
    province: 'กรุงเทพมหานคร',
    postal_code: '10900',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0323',
    sup_type: 'individual',
    sup_name: 'นางสาว การเกตุ ดาวเรือง',
    tax_id: '2340500027319',
    branch_type: '-',
    address_line1: '17 หมู่ 7',
    sub_district: 'คำน้ำแซบ',
    district: 'วารินชำราบ',
    province: 'อุบลราชธานี',
    postal_code: '34190',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0322',
    sup_type: 'individual',
    sup_name: 'รัชนี มหัตเดชกุล',
    tax_id: '3100700084472',
    branch_type: '-',
    address_line1: '350/103 ถนนนางลิ้นจี่',
    sub_district: 'ช่องนนทรี',
    district: 'ยานนาวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10120',
    contact_name: 'คุณเล็ก',
    contact_phone: '098-296-2241',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0321',
    sup_type: 'individual',
    sup_name: 'ร้านถาวรแอ็ดเวอร์ไทซิ่ง โดย นายพันธ์ศักดิ์ ตั้งเดชสัมฤทธิ์',
    tax_id: '3100502359033',
    branch_type: '-',
    contact_phone: '081-563-8896',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0320',
    sup_type: 'individual',
    sup_name: 'นางสาว ผกาวดี บุญชูสกุลยิ่ง',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0319',
    sup_type: 'company',
    sup_name: 'บริษัท ไวด์เอ้าส์ ดีไซน์ แอนด์ บิลด์ จำกัด',
    tax_id: '0105564131842',
    branch_type: 'HO',
    address_line1: '111/1 อาคาร B ห้อง 304-305 ชั้น 3 ถนนประดิษัทธ์มนูธรรม',
    sub_district: 'ลาดพร้าว',
    district: 'ลาดพร้าว',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_phone: '02-116-3326',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'เอกสารส่ง: ห้อง B304,B305 ถ.ประดิษัทธ์มนูธรรม แขวงลาดพร้าว เขตลาดพร้าว กทม.10230 คุณแหม่ม 082-9693527, 02-1163324',
  },
  {
    sup_code: 'S0318',
    sup_type: 'individual',
    sup_name: 'นาย ส่งสุข จิตร์มีทรัพย์',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าจัดส่งไมตรี',
  },
  {
    sup_code: 'S0317',
    sup_type: 'individual',
    sup_name: 'บริษัท วิลล่า นครินทร์ จำกัด',
    branch_type: '-',
    address_line1: '102 ถนนริมคลองบางกะปิ',
    sub_district: 'บางกะปิ',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'บริษัทจัดการบัญชีส่วนกลาง ไหม่แบบ บริษัท เอคิว',
  },
  {
    sup_code: 'S0316',
    sup_type: 'company',
    sup_name: 'บริษัท เค สเปช ดีไซน์ จำกัด',
    tax_id: '0705561001985',
    branch_type: 'HO',
    address_line1: '5/5 หมู่ 9 ต.คลองตาคต',
    district: 'โพธาราม',
    province: 'ราชบุรี',
    postal_code: '70120',
    contact_phone: '097-179-7337',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0315',
    sup_type: 'company',
    sup_name: 'บริษัท ริชเชอร์ เซอร์วิสเซล จำกัด',
    tax_id: '0105566179982',
    branch_type: 'HO',
    address_line1: 'เลขที่ 89/53 ซอยรามคำแหง 94',
    sub_district: 'สะพานสูง',
    district: 'สะพานสูง',
    province: 'กรุงเทพมหานคร',
    contact_phone: '02-095-5254',
    contact_phone2: '096-906-6662',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0314',
    sup_type: 'individual',
    sup_name: 'บริษัท เดอะแกรนด์ โฮม โปรดัก จำกัด',
    tax_id: '0105564148826',
    branch_type: '-',
    address_line1: '594/108 ถนนหทัยราษฎร์',
    sub_district: 'บางชัน',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_name: 'คุณหลิน',
    contact_phone: '063-2124613',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0313',
    sup_type: 'company',
    sup_name: 'บริษัท บี.เอฟ.เอ็ม.ไมโคร จำกัด',
    tax_id: '0105566202950',
    branch_type: 'HO',
    address_line1: '779/20, 779/24 ถนนประชาอุทิศ',
    sub_district: 'สามเสนนอก',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'คุณปู',
    contact_phone: '02-162-0429',
    contact_phone2: '099-395-4426',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    partner_type: 'ลามิเนต',
  },
  {
    sup_code: 'S0312',
    sup_type: 'company',
    sup_name: 'บริษัท วรภาสดี จำกัด',
    branch_type: 'HO',
    address_line1: '82/174 หมู่11 ซอยเอกชัย10 ถนนเอกชัย',
    sub_district: 'บางขุนเทียน',
    district: 'จอมทอง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10150',
    contact_phone: '02-893-8893-4',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, updated = 0, skipped = 0;

  // UPDATE S0334 ด้วยข้อมูลที่ถูกต้อง
  await knex('suppliers').where('sup_code', 'S0334').update({
    sup_name: 'คุณไผลิน วีรขนนท์',
    tax_id: '1119900465927',
    address_line1: '198/221 หมู่ที่ 2 ต.แพรกษาใหม่',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10280',
    note: null,
    updated_at: new Date(),
  });
  console.log('  [UPDATE] S0334 คุณไผลิน วีรขนนท์');
  updated++;

  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) {
      console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`);
      skipped++;
      continue;
    }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }

  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | UPDATE ${updated} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
