/**
 * Import suppliers S0271–S0291 (ข้าม S0285 ไม่มีในระบบเก่า)
 * node scripts/import_suppliers_s271_s291.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0291',
    sup_type: 'company',
    sup_name: 'กรมสรรพากร (อากระ-แสดมปี-online)',
    tax_id: '0105554137465',
    branch_type: 'HO',
    address_line1: 'กรมสรรพากร',
    contact_name: 'กรมสรรพากร',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0290',
    sup_type: 'individual',
    sup_name: 'คุณณวดี พะหุโล',
    tax_id: '1100800162738',
    branch_type: '-',
    address_line1: '125/70 ม.สิรินเอ้าส์ ถ.รัตนาธิเบศร์',
    sub_district: 'ไทรม้า',
    district: 'เมืองนนทบุรี',
    province: 'นนทบุรี',
    postal_code: '11000',
    contact_name: 'คุณแดท',
    contact_phone: '084-044-6556',
    payment_term: 'เงินสด',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0289',
    sup_type: 'individual',
    sup_name: 'หมอปิด',
    branch_type: '-',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0288',
    sup_type: 'individual',
    sup_name: 'นาง สนัภชา มั่งสุวรรณ',
    tax_id: '3610400065869',
    branch_type: '-',
    address_line1: '447 หมู่ที่ 3 ต.เทพารักษ์',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10270',
    payment_term: 'เงินสด',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0287',
    sup_type: 'company',
    sup_name: 'บริษัท เอส เฟอร์ ดีไซน์ จำกัด',
    branch_type: 'HO',
    address_line1: '402 ซอยเอกชัย 76 แขวงคลองบางพราน',
    sub_district: 'คลองบางพราน',
    district: 'บางบอน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10150',
    contact_name: 'คุณสมมาตร',
    contact_phone: '081-911-2630',
    contact_phone2: '02-416-8218',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0286',
    sup_type: 'individual',
    sup_name: 'น.ส. อัญรินทร์ จิระชาติชัยวงษ์',
    branch_type: '-',
    contact_name: 'คุณนา จัดซื้อ บ.ค.อิวะ',
    contact_phone: '064-5876584',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  // S0285 ไม่มีในระบบเก่า ข้ามไป
  {
    sup_code: 'S0284',
    sup_type: 'individual',
    sup_name: 'นายสาอิต ดีราลาภพานิช',
    branch_type: '-',
    contact_name: 'คุณด้น',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0283',
    sup_type: 'individual',
    sup_name: 'สมมาตร อังสุวิจิตกุล',
    branch_type: '-',
    contact_name: 'คุณสมมาตร อังสุวิจิตกุล',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าคอมมิชชัน',
  },
  {
    sup_code: 'S0282',
    sup_type: 'company',
    sup_name: 'บริษัท โยโกแทค ซิสเต็ม จำกัด',
    tax_id: '0105564004379',
    branch_type: 'HO',
    address_line1: '14 ซอยเฉลิมพระเกียรติ ร.9 ซอย 31',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '095-9206970',
    contact_phone2: '081-7738631',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'วางบิล / รับเช็ค · ราง และ ม่านม้วน · โทร 02-74730158',
  },
  {
    sup_code: 'S0281',
    sup_type: 'individual',
    sup_name: 'จันทร์ธิมา คล้ายบัว',
    tax_id: '1102700270662',
    branch_type: '-',
    address_line1: '33/1 ซอยอ่อนนุช 71',
    sub_district: 'ประเวศ',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'เฟิร์น',
    contact_phone: '062-1952129',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'BD 31 พ.ค. 2536',
  },
  {
    sup_code: 'S0280',
    sup_type: 'company',
    sup_name: 'บริษัท ไอคอม เทด จำกัด',
    tax_id: '0105547025029',
    branch_type: 'HO',
    address_line1: '46/7 อาคารรุ่งโรจน์ธนกุล (ตึก A) ชั้น 7 ถนนรัชดาภิเษก',
    sub_district: 'ห้วยขวาง',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_phone: '02-203-7599',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'หักค่าลิขสิทธิ์ 3%',
  },
  {
    sup_code: 'S0279',
    sup_type: 'individual',
    sup_name: 'คุณจันทร์ฉาย หอวิมาลย์ (J.C Fabric)',
    tax_id: '0107563000037',
    branch_type: '-',
    address_line1: '321 หมู่ 8',
    sub_district: 'หนองจ้อม',
    district: 'สันทราย',
    province: 'เชียงใหม่',
    contact_name: 'คุณจันทร์ฉาย',
    contact_phone: '0814735149',
    payment_term: 'เงินสด',
    withholding_tax: '3',
    note: 'ผ้าใยกัญชง',
  },
  {
    sup_code: 'S0278',
    sup_type: 'company',
    sup_name: 'Dilo Products Co., Ltd.',
    tax_id: '0115555019288',
    branch_type: 'HO',
    address_line1: '289/4-5 หมู่ 3 ซอยกิ่งแก้ว 25/1',
    sub_district: 'ราชาเทวะ',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'คุณโม',
    contact_phone: '084-1618900',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0277',
    sup_type: 'company',
    sup_name: 'บริษัท สลิม.เทค จำกัด',
    branch_type: 'HO',
    address_line1: '63 หมู่ 4',
    sub_district: 'คลองสี่',
    district: 'คลองหลวง',
    province: 'ปทุมธานี',
    postal_code: '12120',
    contact_name: 'เซลส์คุณออย',
    contact_phone: '0851554597',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0276',
    sup_type: 'individual',
    sup_name: 'นางสาวพัทร์ศรัณย์ เกิดสมบูรณ์',
    tax_id: '3720700178587',
    branch_type: '-',
    address_line1: '2453 ซอยพัฒนาการ 47',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'ที่อ้อ',
    contact_phone: '0851600930',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ทุกครั้งที่โอนเงินของวายเฟอร์นิเจอร์ ให้เช็คเลขบัญชีกับพี่อ้อก่อน',
  },
  {
    sup_code: 'S0275',
    sup_type: 'company',
    sup_name: 'ห้างหุ้นส่วนจำกัด ออฟฟิส พริ้นท์',
    branch_type: 'BR',
    branch_no: '00002',
    address_line1: '55 อาคารซีดอนสแควร์ ห้อง ITB 15-16 ชั้น B1 ถนนศรีนครินทร์',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '02-7218717',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'Print Express Seacon',
  },
  {
    sup_code: 'S0274',
    sup_type: 'individual',
    sup_name: 'คุณจริยา บริสุทธิ์บัวทิพย์',
    branch_type: '-',
    address_line1: '1-1/1-3 ถนนประชาชื่น',
    sub_district: 'บางซื่อ',
    district: 'บางซื่อ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10800',
    contact_phone: '02-585-5034',
    contact_phone2: '081-913-2561',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'หจก.เอส.เอส.ศรีสุวรรณ',
  },
  {
    sup_code: 'S0273',
    sup_type: 'company',
    sup_name: 'หจก.เอส เอส ศรีสุวรรณขายผ้า',
    tax_id: '0103537014651',
    branch_type: 'HO',
    address_line1: '1,1-1/1-3 ถนนประชาชื่น',
    sub_district: 'บางซื่อ',
    district: 'บางซื่อ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10800',
    contact_phone: '02-911-4219',
    contact_phone2: '02-587-3153',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0272',
    sup_type: 'individual',
    sup_name: 'เฮอริเดนโปร',
    branch_type: '-',
    address_line1: '263/2 ถนนเฉลิมพระเกียรติ ร.9',
    sub_district: 'ประเวศ',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณกุ้ง',
    contact_phone: '089-4456613',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ร้านปัก',
  },
  {
    sup_code: 'S0271',
    sup_type: 'individual',
    sup_name: 'นายโจ รีสอร์ท',
    branch_type: '-',
    address_line1: '216/1 หมู่ 12',
    sub_district: 'หมูสี',
    district: 'ปากช่อง',
    province: 'นครราชสีมา',
    postal_code: '30130',
    contact_name: 'คุณโจ รีสอร์ท',
    contact_phone: '091-7591246',
    contact_phone2: '044-000519',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'อัพเดตล่าสุด เดือน 6/67 ที่เป็นพัก โอนเข้าบัญชีนี้',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) {
      console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`);
      skipped++;
      continue;
    }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
