/**
 * Import suppliers S0138–S0189 (รวม S0155, S0164 = ว่าง)
 * node scripts/import_suppliers_s138_s189.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0189',
    sup_type: 'company',
    sup_name: 'บริษัท ที อี ซี กรุ๊ป จำกัด',
    tax_id: '0105542043941',
    branch_type: 'HO',
    address_line1: '22 ซอยเสรีไทย 44 แยก 5 แขวงคันนายาว',
    sub_district: 'คันนายาว',
    district: 'คันนายาว',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_name: 'คุณจุฟ้า',
    contact_phone: '02-379-8580-1',
    contact_phone2: '086-6417-7451-2',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'จำหน่าย+ซ่อม Printer',
  },
  {
    sup_code: 'S0188',
    sup_type: 'company',
    sup_name: 'บริษัท จัดหางาน นาซ่าลาดพร้าว 48 จำกัด',
    tax_id: '0105559010668',
    branch_type: 'HO',
    address_line1: '1098 ถ.ลาดพร้าว แขวงสามแสนนอก',
    sub_district: 'สามแสนนอก',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'บจก.จัดหางาน นาซ่าลาดพร้าว 48',
    contact_phone: '021183721',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'บริษัทจัดหาแม่บ้าน',
  },
  {
    sup_code: 'S0187',
    sup_type: 'company',
    sup_name: 'บริษัท โดเวอร์ (ประเทศไทย) จำกัด',
    tax_id: '0105546101627',
    branch_type: 'HO',
    address_line1: '75/104-106 อาคารโอเชียนทาวเวอร์ 2 ชั้น 38 ซอยสุขุมวิท 19 ถนนสุขุมวิท',
    sub_district: 'คลองเดิมเหนือ',
    district: 'วัฒนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10110',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'เครื่องกรองน้ำ · 1,190 บาท/เดือน วันที่ 20 · สำรองจ่ายผ่านบัตร ศลิษา',
  },
  {
    sup_code: 'S0186',
    sup_type: 'individual',
    sup_name: 'นายองอาจ จงจอหอ',
    tax_id: '3301300166730',
    branch_type: '-',
    address_line1: '25 หมู่ 5 ต.ดอนยาวใหญ่',
    district: 'โนนแดง',
    province: 'นครราชสีมา',
    postal_code: '30360',
    contact_name: 'คุณองอาจ',
    contact_phone: '096-809-6739',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่ารถขนขยะ',
  },
  {
    sup_code: 'S0185',
    sup_type: 'company',
    sup_name: 'บริษัท ไทย โอปอฟอลลิ่ง จำกัด',
    tax_id: '0105547021490',
    branch_type: 'HO',
    address_line1: '116/83 หมู่ที่ 9 ซ.ทรัพย์โสภณ ต.บางปลา',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'คุณกฤษดา',
    contact_phone: '081-423-3732',
    contact_phone2: '02-706-5005',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'โรงงานพ่นสี อุตสาหกรรม',
  },
  {
    sup_code: 'S0184',
    sup_type: 'company',
    sup_name: 'ธนาคารทิสโก้สินเชื่อประกันภัย (รถบริษัท กูณ 656 K.Puk)',
    branch_type: 'HO',
    address_line1: 'อาคาร Tisco Tower ชั้น 1 ถ.สาทรเหนือ',
    sub_district: 'สีลม',
    district: 'บางรัก',
    province: 'กรุงเทพมหานคร',
    postal_code: '10500',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'สินเชื่อรถ CX-5 · 22,184 บาท/เดือน วันที่ 20',
  },
  {
    sup_code: 'S0183',
    sup_type: 'individual',
    sup_name: 'นาง ดวงเดือน อมตฉายา',
    tax_id: '5400800002544',
    branch_type: '-',
    address_line1: '8/105 ซ.บางนา-ตราด 46 แขวงบางนาใต้',
    sub_district: 'บางนาใต้',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'เดือน',
    contact_phone: '0897645982',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าแรง part-time',
  },
  {
    sup_code: 'S0182',
    sup_type: 'individual',
    sup_name: 'นาย เชียง เรืองสาย',
    tax_id: '3330700571665',
    branch_type: '-',
    address_line1: '44 หมู่ที่ 7 ต.พิมาย',
    district: 'ปรางค์กู่',
    province: 'ศรีสะเกษ',
    postal_code: '33170',
    contact_name: 'คุณเชียง',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าแรงช่างสี',
  },
  {
    sup_code: 'S0181',
    sup_type: 'individual',
    sup_name: 'นาง สดารัตน์ กุลพินิจ',
    tax_id: '1100700563846',
    branch_type: '-',
    address_line1: '587/405 หมู่ 2 ต.บางใหม่',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    contact_name: 'คุณอั้น',
    contact_phone: '089-651-2370',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'เริ่มงาน 01/04/2023 · ค่าแรง part-time',
  },
  {
    sup_code: 'S0180',
    sup_type: 'individual',
    sup_name: 'นายเอกยุย พิจารณ์',
    tax_id: '3920600325098',
    branch_type: '-',
    address_line1: '109/505 ถนนเพชรกษาใหม่ ต.ลำพะยา',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10270',
    contact_name: 'คุณเอก',
    contact_phone: '089-891-8431',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'Part-Time ค่าเขียนโปรแกรม',
  },
  {
    sup_code: 'S0179',
    sup_type: 'company',
    sup_name: 'บริษัท พีจี ไอ คอนแทรคเดอร์ จำกัด',
    tax_id: '0105548145711',
    branch_type: 'HO',
    address_line1: '1 ซอยพระรามา9 2 62 แยก 2-4 แขวงแสมดำ',
    sub_district: 'แสมดำ',
    district: 'บางขุนเทียน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10150',
    contact_phone: '098-826-3115',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ฟิล์ม อาคาร',
  },
  {
    sup_code: 'S0178',
    sup_type: 'company',
    sup_name: 'บริษัท ฟรายเดย์ โฮมโมชั่น จำกัด',
    tax_id: '0105564160109',
    branch_type: 'HO',
    address_line1: '64/47 ซอย ราษฎร์พัฒนา 1 แขวงราษฎร์พัฒนา',
    sub_district: 'ราษฎร์พัฒนา',
    district: 'สะพานสูง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10240',
    contact_name: 'คุณสุวัฒน์',
    contact_phone: '081-374-9741',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'อุปกรณ์มอเตอร์',
  },
  {
    sup_code: 'S0177',
    sup_type: 'individual',
    sup_name: 'นางสาว นภสร สุขเกษม',
    branch_type: '-',
    contact_name: 'ไอซ์',
    contact_phone: '0875454865',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าแรง part-time',
  },
  {
    sup_code: 'S0176',
    sup_type: 'individual',
    sup_name: 'นางสาว ปานทิพย์ ปัดตานัง',
    tax_id: '1110100126321',
    branch_type: '-',
    address_line1: '10/142 ซ.เฉลิมพระเกียรติ ร.9 ซ.30 แยก14-1',
    sub_district: 'ดอกไม้',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    contact_name: 'นิว',
    contact_phone: '095-256-6437',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าแรง part-time',
  },
  {
    sup_code: 'S0175',
    sup_type: 'company',
    sup_name: 'อีซีพาส / EASY PASS / ภูณ656',
    branch_type: 'HO',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าทางด่วน K.ปุ๊ก ภูณ656',
  },
  {
    sup_code: 'S0174',
    sup_type: 'individual',
    sup_name: 'นางสาว เลขา อุทัยรังษี',
    tax_id: '3100201482685',
    branch_type: '-',
    address_line1: '21 หมู่ 5 ต.วังใหม่',
    district: 'ป่าบอน',
    province: 'พัทลุง',
    postal_code: '93170',
    contact_name: 'จอย',
    contact_phone: '0626539264',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าคอมมิชชัน พี่จอย',
  },
  {
    sup_code: 'S0173',
    sup_type: 'company',
    sup_name: 'บริษัท ชูติมา (1992) จำกัด',
    branch_type: 'HO',
    address_line1: '998 ถนนลาดพร้าว แขวงบางนา',
    sub_district: 'บางนา',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'Sales คุณกัลยาณี / คุณไบร์ท / นก',
    contact_phone: '02-349-4651-3',
    contact_phone2: '094-989-9589',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าวอลล์เปเปอร์ · www.chitima.co.th',
  },
  {
    sup_code: 'S0172',
    sup_type: 'individual',
    sup_name: 'นาย สุริยา แฝงดาหาร',
    nickname: 'ช่างยะ',
    tax_id: '3401700906110',
    branch_type: '-',
    address_line1: '213 หมู่ 9 ต.บ้านโคก',
    district: 'โคกโพธิ์ไชย',
    province: 'ขอนแก่น',
    postal_code: '40160',
    contact_name: 'ช่างยะ',
    contact_phone: '086-711-7511',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างติดตั้งวอลล์เปเปอร์',
  },
  {
    sup_code: 'S0171',
    sup_type: 'company',
    sup_name: 'บริษัท ทีพีเอ็นที จำกัด',
    tax_id: '0105562103612',
    branch_type: 'HO',
    address_line1: '1562/119 ถนนประชาราษฎร์ 1',
    sub_district: 'บางซื่อ',
    district: 'บางซื่อ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10800',
    contact_phone: '02-333-0666',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0170',
    sup_type: 'company',
    sup_name: 'บริษัท ไทยเว็บ คอร์ปอเรชั่น จำกัด',
    tax_id: '0105553027232',
    branch_type: 'HO',
    address_line1: '2/152 ซอยเพชรเกษม 114',
    sub_district: 'หนองค้างพลู',
    district: 'หนองแขม',
    province: 'กรุงเทพมหานคร',
    postal_code: '10160',
    contact_phone: '02-810-8300',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าโฆษณา สมัครงาน',
  },
  {
    sup_code: 'S0169',
    sup_type: 'individual',
    sup_name: 'นางสาว ปุณยนุช โนจา',
    tax_id: '1579900167337',
    branch_type: '-',
    address_line1: '78 หมู่ 13 ต.ทุ่งก่อ',
    district: 'เวียงเชียงรุ้ง',
    province: 'เชียงราย',
    postal_code: '57350',
    contact_name: 'คุณแจ็ด',
    contact_phone: '0979603536',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าแรงช่างไม้',
  },
  {
    sup_code: 'S0168',
    sup_type: 'individual',
    sup_name: 'นาย รณกร อนันตศิลป์',
    tax_id: '1209700615983',
    branch_type: '-',
    contact_name: 'กร',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'พนักงาน part-time',
  },
  {
    sup_code: 'S0167',
    sup_type: 'company',
    sup_name: 'บริษัท บี.เอฟ.เอ็ม. จำกัด',
    tax_id: '0105539069721',
    branch_type: 'HO',
    address_line1: '779/20, 779/24 ถนนประชาอุทิศ',
    sub_district: 'สามแสนนอก',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'เซลส์คุณปู',
    contact_phone: '02-162-0429',
    contact_phone2: '099-395-4426',
    payment_term: 'เครดิต',
    withholding_tax: 'ไม่หัก',
    note: 'ลามิเนต · วางบิล / รับเช็ค',
  },
  {
    sup_code: 'S0166',
    sup_type: 'individual',
    sup_name: 'นาย วีเชียร อมรตระกูล',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: '*ข้อมูลเก่า (ยกเลิก เนื่องจากมีการเปลี่ยนแปลงเลขที่บัญชี)',
  },
  {
    sup_code: 'S0165',
    sup_type: 'company',
    sup_name: 'บริษัท ทิงค์เน็ต จำกัด',
    tax_id: '0125543004205',
    branch_type: 'HO',
    address_line1: '323 อาคารยูไนเต็ดเซ็นเตอร์ ชั้น 6 ห้อง 601 ถนนสีลม',
    sub_district: 'สีลม',
    district: 'บางรัก',
    province: 'กรุงเทพมหานคร',
    postal_code: '10500',
    contact_phone: '02-480-9999',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'jobthai.com · ค่าสมัครงาน 2% ยืนยันการโอนเงิน sale@jobthai.com',
  },
  {
    sup_code: 'S0164',
    sup_type: 'individual',
    sup_name: 'ว่าง',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0163',
    sup_type: 'individual',
    sup_name: 'นางสาว จันจิรา บุญมี',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าแรงโปรแกรมเมอร์ คุณแก้ว',
  },
  {
    sup_code: 'S0162',
    sup_type: 'individual',
    sup_name: 'นางสาว ศลิษา แสงหิรัญ (บัตรเครดิต K-Bank)',
    branch_type: '-',
    address_line1: 'เลขที่ 99/73 ถ.เฉลิมพระเกียรติ ร.9',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณปุ๊ก',
    contact_phone: '081-432-5753',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0161',
    sup_type: 'company',
    sup_name: 'ร้านโต้ะแดงเฟอร์นีเจอร์ จตุจักร',
    branch_type: 'HO',
    address_line1: '808/304 โครงการ บีโอ อิ ถนนกำแพงเพชร แขวงลาดยาว เขตจตุจักร',
    sub_district: 'ลาดยาว',
    district: 'จตุจักร',
    province: 'กรุงเทพมหานคร',
    postal_code: '10900',
    contact_phone: '084-035-1806',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'โต๊ะโครงเหล็กสั่งทำ',
  },
  {
    sup_code: 'S0160',
    sup_type: 'company',
    sup_name: 'บริษัท ทีซีเอ็ม คอร์ปอเรชั่น จำกัด',
    tax_id: '0107537001021',
    branch_type: 'HO',
    address_line1: '2044/24 ถนนเพชรบุรีตัดใหม่ แขวงบางกะปิ',
    sub_district: 'บางกะปิ',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'ภาณุวัต หอมสุวรรณ',
    contact_phone: '089-144-1980',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'จำหน่ายพรม',
  },
  {
    sup_code: 'S0159',
    sup_type: 'company',
    sup_name: 'I.T.Solution Computer (Thailand) Co.,Ltd.',
    tax_id: '0105544033853',
    branch_type: 'HO',
    address_line1: '937 ถนนศรีนครินทร์ แขวงสวนหลวง',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '02-725-6400',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'จำหน่ายโปรแกรม · ดูป S0211',
  },
  {
    sup_code: 'S0158',
    sup_type: 'individual',
    sup_name: 'นางสาว สุพาภรณ์ มุ่งดี',
    tax_id: '1311000110783',
    branch_type: '-',
    address_line1: '20/2 ซ.เฉลิมพระเกียรติ ร.9 ซ.48 แยก 1',
    sub_district: 'ดอกไม้',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · โรงงานช.48',
  },
  {
    sup_code: 'S0157',
    sup_type: 'individual',
    sup_name: 'นาย สิขิต นาจดี',
    tax_id: '1469900145326',
    branch_type: '-',
    address_line1: 'เลขที่ 109 หมู่ 12 ต.หลักเมือง',
    district: 'กมลาไสย',
    province: 'กาฬสินธุ์',
    postal_code: '46130',
    contact_name: 'ช่างจ่อย',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างติดตั้งวอลล์เปเปอร์',
  },
  {
    sup_code: 'S0156',
    sup_type: 'individual',
    sup_name: 'นาย ณัฐพล แก้วพลับ',
    tax_id: '1103700979191',
    branch_type: '-',
    address_line1: 'เลขที่ 42/70 หมู่5 แขวงจอมทอง',
    sub_district: 'จอมทอง',
    district: 'จอมทอง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10150',
    contact_name: 'โอ้ด',
    contact_phone: '0828574707',
    contact_phone2: '0886237463',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'BD 14 ธ.ค. 2535',
  },
  {
    sup_code: 'S0155',
    sup_type: 'individual',
    sup_name: 'ว่าง',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0154',
    sup_type: 'individual',
    sup_name: 'นาง วิเชียร จิ้วลาย',
    branch_type: '-',
    address_line1: 'เลขที่ 10 ซ.สัมพันธ์ 1 แยก2 แขวงกระทุ่มราย',
    sub_district: 'กระทุ่มราย',
    district: 'หนองจอก',
    province: 'กรุงเทพมหานคร',
    postal_code: '10530',
    contact_phone: '089-6222565',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'สแตนเลส',
  },
  {
    sup_code: 'S0153',
    sup_type: 'individual',
    sup_name: 'นางสาว มณฑา สุวรรณจำรูญ',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'บัญชีบริษัท ลินสิลิน ลิฟวิ่ง จำกัด',
  },
  {
    sup_code: 'S0152',
    sup_type: 'company',
    sup_name: 'บริษัท ไซม์ ดาร์บี้ มาสด้า (ประเทศไทย) จำกัด',
    tax_id: '0205557039412',
    branch_type: 'HO',
    address_line1: 'ถนนศรีนครินทร์ 227/18-19 หมู่ 5 ต.บางเมือง',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10270',
    contact_phone: '02-703-2211',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'จดทะเบียนรถยนต์ · ดูป S0207',
  },
  {
    sup_code: 'S0151',
    sup_type: 'company',
    sup_name: 'ห้างหุ้นส่วนจำกัด ทรัพย์บุญส่ง',
    tax_id: '0143560000580',
    branch_type: 'HO',
    address_line1: 'เลขที่ 24 ม. 6 ต.ลำพระขาว',
    district: 'บางบาล',
    province: 'พระนครศรีอยุธยา',
    postal_code: '13250',
    contact_phone: '081-944-2154',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'อิฐ',
  },
  {
    sup_code: 'S0150',
    sup_type: 'company',
    sup_name: 'บริษัท พงศ์พัฒนากิจ ช่าง จำกัด',
    tax_id: '0105562180323',
    branch_type: 'HO',
    address_line1: 'เลขที่ 123/495 หมู่ 3 ต.บางปลา',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_phone: '02-012-6503',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'หินสังเคราะห์',
  },
  {
    sup_code: 'S0149',
    sup_type: 'company',
    sup_name: 'ห้างหุ้นส่วนจำกัด เอส ซี เอส เทคโนโลยี',
    tax_id: '0133556002336',
    branch_type: 'HO',
    address_line1: 'เลขที่ 53/490 หมู่บ้านพฤกษา 20 หมู่ที่ 2 ซ.2/1 ถนนลำลูกกา',
    district: 'ลำลูกกา',
    province: 'ปทุมธานี',
    postal_code: '12130',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ซ่อมประตูดิจิตอล',
  },
  {
    sup_code: 'S0148',
    sup_type: 'individual',
    sup_name: 'นาย สมหมาย ติวสะอาด',
    tax_id: '5411600048193',
    branch_type: '-',
    address_line1: 'เลขที่ 3 หมู่ที่ 2 ต.หนองเทา',
    district: 'ท่าอุเทน',
    province: 'นครพนม',
    postal_code: '48120',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · ช่างประตูดิจิตอล',
  },
  {
    sup_code: 'S0147',
    sup_type: 'company',
    sup_name: 'บริษัท ศ.รุ่งอนันต์ จำกัด',
    tax_id: '0115547008051',
    branch_type: 'HO',
    address_line1: 'เลขที่ 226/6-7 หมู่ที่ 5 ต.ศรีนครินทร์ ต.บางเมือง',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10270',
    contact_phone: '02-759-9672-73',
    contact_phone2: '02-759-9650',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'สินค้าฮาร์ดแวร์',
  },
  {
    sup_code: 'S0146',
    sup_type: 'company',
    sup_name: 'บริษัท ราชาทรัพย์ จำกัด',
    tax_id: '0125560003009',
    branch_type: 'HO',
    address_line1: 'เลขที่ 212/7 หมู่ที่ 1 ต.บางไผ่',
    district: 'เมืองนนทบุรี',
    province: 'นนทบุรี',
    postal_code: '11000',
    contact_name: 'คุณทิพย์',
    contact_phone: '094-8263249',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'Fitting ตัวล็อก บางโพ',
  },
  {
    sup_code: 'S0145',
    sup_type: 'individual',
    sup_name: 'นางสาว อภิญญา แก้วพลับ',
    tax_id: '1103700478213',
    branch_type: '-',
    address_line1: 'เลขที่ 42/70 ม.5 แขวงจอมทอง',
    sub_district: 'จอมทอง',
    district: 'จอมทอง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10150',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · ค่าคอมมิชชัน',
  },
  {
    sup_code: 'S0144',
    sup_type: 'individual',
    sup_name: 'นางสาว วาสนา สง่าดี (อลูมิเนียม แอดเซทเชอรี่)',
    tax_id: '1100900371355',
    branch_type: '-',
    address_line1: 'เลขที่ 7 ซ.อ่อนนุช 35',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '061-929-8513',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'Fitting อลูมิเนียม · www.aluminum-accessories.com',
  },
  {
    sup_code: 'S0143',
    sup_type: 'company',
    sup_name: 'ธนาคารทิสโก้ สินเชื่อ ประกันภัย (รถบริษัท กูณ 665 K.Pete)',
    branch_type: 'HO',
    address_line1: 'อาคาร Tisco Tower ชั้น 1 ถ.สาทรเหนือ',
    sub_district: 'สีลม',
    district: 'บางรัก',
    province: 'กรุงเทพมหานคร',
    postal_code: '10500',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'สินเชื่อรถ CX-30 · 19,240 บาท/เดือน วันที่ 20',
  },
  {
    sup_code: 'S0142',
    sup_type: 'individual',
    sup_name: 'นาย ธีระชัย จันธิมา',
    tax_id: '3560200208781',
    branch_type: '-',
    address_line1: 'เลขที่ 162 หมู่ 10 ต.ทงสหิน',
    district: 'จุน',
    province: 'พะเยา',
    postal_code: '56150',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ขนขยะ',
  },
  {
    sup_code: 'S0141',
    sup_type: 'individual',
    sup_name: 'นางสาว จินด์ทิพา สุประดิษฐ์',
    tax_id: '3100203547482',
    branch_type: '-',
    address_line1: 'เลขที่ 8/32 หมู่ 8 ต.สำโรงเหนือ',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10270',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '5',
    note: 'ค่าคอมมิชชัน 5%',
  },
  {
    sup_code: 'S0140',
    sup_type: 'company',
    sup_name: 'ร้านมาลีพันธุ์พาณิชย์',
    tax_id: '3100902923653',
    branch_type: 'HO',
    address_line1: 'เลขที่ 322 ถนนพัฒนาการ แขวงประเวศ',
    sub_district: 'ประเวศ',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '02-321-2583',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'เครื่องเหล็ก',
  },
  {
    sup_code: 'S0139',
    sup_type: 'company',
    sup_name: 'บริษัท แอดวานซ์ ไวเลส เน็ทเวอร์ค จำกัด',
    tax_id: '0105548115897',
    branch_type: 'HO',
    address_line1: 'เลขที่ 414 ถนนพหลโยธิน สามเสนใน',
    sub_district: 'สามเสนใน',
    district: 'พญาไท',
    province: 'กรุงเทพมหานคร',
    postal_code: '10400',
    contact_phone: '1175',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'อินเตอร์เน็ต',
  },
  {
    sup_code: 'S0138',
    sup_type: 'company',
    sup_name: 'การไฟฟ้านครหลวง',
    tax_id: '015383987',
    branch_type: 'BR',
    address_line1: '556 ถนนสรรพาวุธ แขวงบางนา',
    sub_district: 'บางนา',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'เลขที่เครื่องวัด 95537688',
    contact_phone: '02-769-3200',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) { console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`); skipped++; continue; }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
