/**
 * Import suppliers S0190–S0230 (รวม S0194 = ว่าง)
 * node scripts/import_suppliers_s190_s230.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0230',
    sup_type: 'company',
    sup_name: 'บริษัท แยสอ อินเดอร์เนชั่นแนล จำกัด',
    tax_id: '0105556088810',
    branch_type: 'HO',
    address_line1: '169/90 ซอยคุ้มอ่อน 27 แขวงท่าแร้ง',
    sub_district: 'ท่าแร้ง',
    district: 'บางเขน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10220',
    contact_name: 'เซลส์คุณณา',
    contact_phone: '061-4054885',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0229',
    sup_type: 'company',
    sup_name: 'บริษัท เอ็มพาสเวอร์ อินเดอร์เนชั่นแนล จำกัด',
    tax_id: '0105554019136',
    branch_type: 'HO',
    address_line1: '6/1 ซ.คุ้มเกล้า 48 ถ.คุ้มเกล้า',
    sub_district: 'ลาดปลาเทียว',
    district: 'ลาดกระบัง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10520',
    contact_phone: '02-3606141',
    contact_phone2: '081-9384701',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'มุ้งจีบ',
  },
  {
    sup_code: 'S0228',
    sup_type: 'company',
    sup_name: 'บริษัท บุณดาวรเชรามิค จำกัด',
    tax_id: '0105535130116',
    branch_type: 'BR',
    address_line1: '15/2 หมู่ 14 ถ.บางนา-ตราด',
    sub_district: 'บางพลีใหญ่',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'สาขาสุวรรณภูมิ',
  },
  {
    sup_code: 'S0227',
    sup_type: 'individual',
    sup_name: 'ว่าง',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0226',
    sup_type: 'individual',
    sup_name: 'นาย สุชาติ เลิศศรัณย์',
    tax_id: '3102400772561',
    branch_type: '-',
    address_line1: '40 ซอยประชาอุทิศ 91/2',
    sub_district: 'ทุ่งครุ',
    district: 'ทุ่งครุ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10140',
    contact_phone: '087-755-8998',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าเช็คแบบสถาปนิก',
  },
  {
    sup_code: 'S0225',
    sup_type: 'individual',
    sup_name: 'นาย ศักย์สุภณ ศรีช่วย',
    tax_id: '3102000294484',
    branch_type: '-',
    address_line1: '73-80 ซ.เจริญพัฒนา 4 แขวงบางชัน',
    sub_district: 'บางชัน',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างปูกระเบื้องออฟฟิศ',
  },
  {
    sup_code: 'S0224',
    sup_type: 'individual',
    sup_name: 'ลัคชูรี ดีไวซ์ (No Vat) / กัลภัสร์ พูนธนพิทักษ์',
    branch_type: '-',
    address_line1: '108/24 ซ.ประเสริฐมนุกิจ 29 ถ.ประเสริฐมนุกิจ',
    sub_district: 'ลาดพร้าว',
    district: 'ลาดพร้าว',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_phone: '091-8078783',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'รางม่านพร้อมอุปกรณ์ม่าน · No Vat',
  },
  {
    sup_code: 'S0223',
    sup_type: 'company',
    sup_name: 'บริษัท ลัคชูรี ดีไวซ์ จำกัด',
    tax_id: '0105560207216',
    branch_type: 'HO',
    address_line1: '108/24 ซ.ประเสริฐมนุกิจ 29 ถ.ประเสริฐมนุกิจ',
    sub_district: 'ลาดพร้าว',
    district: 'ลาดพร้าว',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_phone: '091-8078783',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'รางม่านพร้อมอุปกรณ์ม่าน',
  },
  {
    sup_code: 'S0222',
    sup_type: 'individual',
    sup_name: 'รถบ้านพีอาร์เอ็ม พัฒนาการ',
    branch_type: '-',
    address_line1: '1122 ถนนพัฒนาการตัดใหม่',
    sub_district: 'ประเวศ',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0221',
    sup_type: 'company',
    sup_name: 'บริษัท เน็ตเวิร์ค เทคนิคอล ซิสเต็ม จำกัด',
    tax_id: '0205555037064',
    branch_type: 'HO',
    address_line1: '999/9 อาคารดิ ออฟฟิศเดส เซ็นทรัลเวิลด์ ชั้น 29 ห้อง 2982 ถนนพระรามา 1',
    sub_district: 'ปทุมวัน',
    district: 'ปทุมวัน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10330',
    contact_phone: '0-2107-3466',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0220',
    sup_type: 'individual',
    sup_name: 'นางสาว วลัยพร ทิพย์แก้ว',
    tax_id: '1100703213285',
    branch_type: '-',
    address_line1: '29 ซ.อ่อนนุช 68 แขวงอ่อนนุช',
    sub_district: 'อ่อนนุช',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณลักษณ์',
    contact_phone: '094-894-6968',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '5',
    note: 'ค่าคอมมิชชัน 5% · งานอาสาเฟอร์นีเจอร์',
  },
  {
    sup_code: 'S0219',
    sup_type: 'individual',
    sup_name: 'นางสาว จีราภรณ์ แสนกล้า',
    tax_id: '1530900049107',
    branch_type: '-',
    address_line1: '308 หมู่ที่ 6 ต.ผักขวง',
    district: 'ทองแสนขัน',
    province: 'อุตรดิตถ์',
    postal_code: '53230',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0218',
    sup_type: 'company',
    sup_name: 'บริษัท ศ.ดีวา การช่าง จำกัด',
    tax_id: '0105556088640',
    branch_type: 'HO',
    address_line1: 'เลขที่ 776/45 ซ.พัฒนาการ 38',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0217',
    sup_type: 'company',
    sup_name: 'กรมสรรพากรเพื่อรับชำระหนี้ กยส',
    tax_id: '0994000212038',
    branch_type: 'HO',
    address_line1: 'เลขที่ 89 อาคาร เอไอเอ แคปปิตอล เซ็นเตอร์ ชั้น 5-6 ถนนรัชดาภิเษก',
    sub_district: 'ดินแดง',
    district: 'ดินแดง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10400',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0216',
    sup_type: 'company',
    sup_name: 'บริษัท เซน่า อินเดอร์เนชั่นแนล กรุ๊ป จำกัด',
    tax_id: '0105535001227',
    branch_type: 'HO',
    address_line1: '2439 ซ.พัฒนาการ 47 ถนนพัฒนาการ',
    sub_district: 'พัฒนาการ',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '0-2720-4744-6',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0215',
    sup_type: 'individual',
    sup_name: 'นายพุทธกร ช่างเสวก (นายโจ รีสอร์ท ที่พักเขาใหญ่)',
    branch_type: '-',
    address_line1: '216 หมู่ 12 ต.หมูสี',
    district: 'ปากช่อง',
    province: 'นครราชสีมา',
    postal_code: '30130',
    contact_phone: '097-243-7336',
    contact_phone2: '091-759-1246',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0214',
    sup_type: 'company',
    sup_name: 'บริษัท คอมเซเว่น จำกัด (มหาชน)',
    tax_id: '0107557000462',
    branch_type: 'HO',
    address_line1: '549/1 ถนนสรรพาวุธ แขวงบางนาใต้',
    sub_district: 'บางนาใต้',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_phone: '063-887-3957',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0213',
    sup_type: 'individual',
    sup_name: 'MS. NAN KHIN OHN',
    branch_type: '-',
    address_line1: '99/73',
    contact_name: 'โม แม่บ้าน พม่า',
    contact_phone: '0648309565',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'แม่บ้าน พม่าโม',
  },
  {
    sup_code: 'S0212',
    sup_type: 'company',
    sup_name: 'บริษัท ณารา เฟอร์นีเจอร์ส จำกัด',
    tax_id: '0105561078053',
    branch_type: 'HO',
    address_line1: '1 ซอยพุทธบูชา 41 ถนนพุทธบูชา',
    sub_district: 'บางมด',
    district: 'ทุ่งครุ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10140',
    contact_phone: '063-236-6451',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0211',
    sup_type: 'company',
    sup_name: 'บริษัท ไอ.ที. โซลูชั่น คอมทิวเตอร์ (ไทยแลนด์) จำกัด',
    tax_id: '0105544033853',
    branch_type: 'HO',
    address_line1: '937 ถนนศรีนครินทร์ แขวงสวนหลวง',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '0-2725-6400',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0210',
    sup_type: 'individual',
    sup_name: 'ร้านปริญ โมบาย',
    branch_type: '-',
    address_line1: 'ห้างซีคอนศรีนครินทร์ บูธ19 หน้า Shop HUAWEI',
    contact_phone: '085-952-6484',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0209',
    sup_type: 'individual',
    sup_name: 'M.B computer',
    branch_type: '-',
    address_line1: 'ห้างซีคอนสแควร์ ITB18C ชั้น B1',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '062-458-7121',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0208',
    sup_type: 'company',
    sup_name: 'กรมพัฒนาธุรกิจการค้า',
    branch_type: 'HO',
    address_line1: '563 ถ.นนทบุรี',
    district: 'เมืองนนทบุรี',
    province: 'นนทบุรี',
    postal_code: '11000',
    contact_phone: '0-2547-5994',
    contact_phone2: '0-2547-5160',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0207',
    sup_type: 'company',
    sup_name: 'บริษัท ไซม์ ดาร์บี้ มาสด้า (ประเทศไทย) จำกัด',
    tax_id: '0105544056411',
    branch_type: 'HO',
    address_line1: '452 ถ.ศรีนครินทร์ แขวงหนองบอน',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0206',
    sup_type: 'company',
    sup_name: 'บริษัท เอ็นโนวา คอร์เปอเรชั่น จำกัด',
    tax_id: '0125561001051',
    branch_type: 'HO',
    address_line1: '89/65 หมู่ 5 ต.บางศรีเมือง',
    district: 'เมืองนนทบุรี',
    province: 'นนทบุรี',
    postal_code: '11000',
    contact_name: 'คุณกำพลศักดิ์',
    contact_phone: '0865566940',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าเขียนแบบ',
  },
  {
    sup_code: 'S0205',
    sup_type: 'company',
    sup_name: 'บริษัท นิยวาร์ดทินอ่อนและแกรนิต จำกัด',
    tax_id: '0105526046892',
    branch_type: 'HO',
    address_line1: '11/6 ถนนคลองต้นเจ็กยัน แขวงนวลจันทร์',
    sub_district: 'นวลจันทร์',
    district: 'บึงกุ่ม',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_phone: '02-508-0778',
    contact_phone2: '02-508-0503',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'จำหน่ายหินอ่อนและแกรนิต',
  },
  {
    sup_code: 'S0204',
    sup_type: 'individual',
    sup_name: 'นาย คณิต ชาลีบัว',
    nickname: 'ช่างทัก',
    tax_id: '1640300006431',
    branch_type: '-',
    address_line1: '59/39 หมู่ 3 หมู่บ้านแลนซีโอซิตี้ ต.ท่าอิฐ',
    district: 'ปากเกร็ด',
    province: 'นนทบุรี',
    postal_code: '11120',
    contact_name: 'ช่างทัก',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างวอลล์ส (ช่างทัก)',
  },
  {
    sup_code: 'S0203',
    sup_type: 'individual',
    sup_name: 'นายธนโชค รัตนวราห',
    tax_id: '1200101741649',
    branch_type: '-',
    address_line1: '997/438 หมู่ที่ 13 ต.ราชาเทวะ',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'โฟล์ด',
    contact_phone: '0659578922',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'เริ่มงาน 3/03/2023 · BD-30 ต.ค. 2540',
  },
  {
    sup_code: 'S0202',
    sup_type: 'individual',
    sup_name: 'น.ส. เจริญพงษ์ บุญปลุก',
    tax_id: '3100903772535',
    branch_type: '-',
    address_line1: '56/145 หมู่ที่ 4 ต.บางพลีใหญ่',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'ที่มี',
    contact_phone: '0984639510',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'เริ่มงาน 21/04/2023',
  },
  {
    sup_code: 'S0201',
    sup_type: 'individual',
    sup_name: 'น.ส. รัตนาภรณ์ อนุพัฒนกุล',
    tax_id: '1349901006380',
    branch_type: '-',
    address_line1: '274 ถ.พลโชชัย ต.ในเมือง',
    district: 'เมืองอุบลราชธานี',
    province: 'อุบลราชธานี',
    postal_code: '34000',
    contact_name: 'หมิว',
    contact_phone: '0827512131',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'เริ่มงานวันที่ 24/04/2023',
  },
  {
    sup_code: 'S0200',
    sup_type: 'company',
    sup_name: 'บริษัท ดิโล โปรดักส์ กรุ๊ป จำกัด',
    tax_id: '0115555019288',
    branch_type: 'HO',
    address_line1: '289/4-5 ม.13 ซ.กิ่งแก้ว 25/1 ต.ราชาเทวะ',
    sub_district: 'ราชาเทวะ',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'คุณพัทพัฒน์ชัย',
    contact_phone: '084-161-8900',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'กระเบื้องไวนิล · ดูป S0278',
  },
  {
    sup_code: 'S0199',
    sup_type: 'company',
    sup_name: 'บริษัท อาเชียแฟบริค (ประเทศไทย) จำกัด',
    tax_id: '0105549092700',
    branch_type: 'HO',
    address_line1: '22 ซ.ศรีนครินทร์ 56',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'Sales คุณสวรรค์ พุ่มประเสริฐ',
    contact_phone: '086-981-9988',
    contact_phone2: '02-059-4410',
    payment_term: 'เครดิต',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน · วางบิล / รับเช็ค',
  },
  {
    sup_code: 'S0198',
    sup_type: 'company',
    sup_name: 'บริษัท เดคคอร์ อาร์ต แฟบริค จำกัด',
    tax_id: '0105546072180',
    branch_type: 'HO',
    address_line1: '119/599 ม.6 ถ.นวมินทร์',
    sub_district: 'คลองกุ่ม',
    district: 'บึงกุ่ม',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_name: 'คุณสมชาย อมรชากิจ (แก้ว)',
    contact_phone: '02-948-4592',
    contact_phone2: '02-948-6069',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน มู่ลี่ไม้',
  },
  {
    sup_code: 'S0197',
    sup_type: 'company',
    sup_name: 'บริษัท แคปปิตอล คาร์เปท จำกัด',
    tax_id: '0105545076939',
    branch_type: 'HO',
    address_line1: '32 ซ.อุดมสุข 31 ถ.สุขุมวิท 103',
    sub_district: 'บางนาจาก',
    district: 'พระโขนง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'คุณจี้ดา มีประทัง',
    contact_phone: '086-016-7832',
    contact_phone2: '02-383-8850',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'พื้นพรม',
  },
  {
    sup_code: 'S0196',
    sup_type: 'company',
    sup_name: 'บริษัท เจริญ เดคคอร์ อินเดอร์เนชั่นแนล จำกัด',
    tax_id: '0105546077912',
    branch_type: 'HO',
    address_line1: '300 ซ.เอกมัย 16 สุขุมวิท 63',
    sub_district: 'คลองตันเหนือ',
    district: 'วัฒนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10110',
    contact_name: 'คุณเวราพร รอดไทยมูลย์',
    contact_phone: '089-518-3010',
    contact_phone2: '02-381-8388',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0195',
    sup_type: 'company',
    sup_name: 'P.N.CURTAIN',
    branch_type: 'HO',
    address_line1: '141/70 ซ.พัฒนาการ 29 ถ.พัฒนาการ',
    sub_district: 'สวนหลวง',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณประทีป',
    contact_phone: '086-345-1772',
    contact_phone2: '083-608-8751',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านสวย สไตล์ยุโรป',
  },
  {
    sup_code: 'S0194',
    sup_type: 'individual',
    sup_name: 'ว่าง',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0193',
    sup_type: 'company',
    sup_name: 'บริษัท เอ็ม.เอส.ดับบลิว.โซลูชั่น แอนด์ เชอร์วิส จำกัด',
    tax_id: '0125564018701',
    branch_type: 'HO',
    address_line1: '399 ซ.แรวด์ 57 ต.ตลาดขวัญ',
    district: 'เมืองนนทบุรี',
    province: 'นนทบุรี',
    postal_code: '11000',
    contact_name: 'คุณนนทชัย',
    contact_phone: '081-826-9719',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ชัพพลายเออร์ติดตั้งฟิล์ม',
  },
  {
    sup_code: 'S0192',
    sup_type: 'company',
    sup_name: 'บริษัท เวิลด์ เลเซอร์ เซ็นเตอร์',
    tax_id: '0105532115159',
    branch_type: 'HO',
    address_line1: '231 ถ.เจริญรัต แขวงคลองสาน',
    sub_district: 'คลองสาน',
    district: 'คลองสาน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10600',
    contact_name: 'คุณสุ้ง',
    contact_phone: '086-341-3181',
    contact_phone2: '02-861-6172',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน ผ้ากันน้ำ',
  },
  {
    sup_code: 'S0191',
    sup_type: 'company',
    sup_name: 'บริษัท วีคอนเซ็ปต์ จำกัด',
    tax_id: '0105559099545',
    branch_type: 'HO',
    address_line1: '2944 ถ.พัฒนาการ แขวงสวนหลวง',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณภัทร หงษ์จันทร์',
    contact_phone: '02-722-2839',
    contact_phone2: '085-989-9650',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'อุปกรณ์ห่วงสายรวมม่านโลก้',
  },
  {
    sup_code: 'S0190',
    sup_type: 'company',
    sup_name: 'บริษัท พีเอสเอ คอร์ปอเรชั่น จำกัด',
    tax_id: '0745559001591',
    branch_type: 'HO',
    address_line1: '1082/3 ถนนกรุงเกษม แขวงคลองมหานาค',
    sub_district: 'คลองมหานาค',
    district: 'ป้อมปราบศัตรูพ่าย',
    province: 'กรุงเทพมหานคร',
    postal_code: '10100',
    contact_phone: '098-885-5844',
    contact_phone2: '02-628-3577',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ริบบิ้น LINCON',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) { console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`); skipped++; continue; }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
