/**
 * Import suppliers S0078–S0137
 * node scripts/import_suppliers_s078_s137.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0137',
    sup_type: 'company',
    sup_name: 'กรมพัฒนาธุรกิจการค้า (สาขาศรีนครินทร์)',
    branch_type: 'BR',
    withholding_tax: 'ไม่หัก',
    note: 'คัดเอกสารบริษัท',
  },
  {
    sup_code: 'S0136',
    sup_type: 'individual',
    sup_name: 'นาย วีระเดช เดชะพรมวงค์',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างบุเฟอร์นิเจอร์',
  },
  {
    sup_code: 'S0135',
    sup_type: 'individual',
    sup_name: 'นาย รัฐพงศ์ สมกันทา',
    branch_type: '-',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · โรงงานช.48',
  },
  {
    sup_code: 'S0134',
    sup_type: 'company',
    sup_name: 'การทางพิเศษแห่งประเทศไทย',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ทางด่วน',
  },
  {
    sup_code: 'S0133',
    sup_type: 'company',
    sup_name: 'Google Asia Pacific Pte. Ltd',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'Google AD',
  },
  {
    sup_code: 'S0132',
    sup_type: 'company',
    sup_name: 'Facebook Ireland Limited',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0131',
    sup_type: 'company',
    sup_name: 'ไอพลัสวีว โดย นายทวีศักดิ์ พรหมมาศ',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'มาเก็ตติ้งออนไลน์',
  },
  {
    sup_code: 'S0130',
    sup_type: 'individual',
    sup_name: 'นาย ธราเทพ ยาผา',
    branch_type: '-',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าทำความสะอาด',
  },
  {
    sup_code: 'S0129',
    sup_type: 'company',
    sup_name: 'การประปานครหลวง',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าน้ำ',
  },
  {
    sup_code: 'S0128',
    sup_type: 'individual',
    sup_name: 'คุณ สุพรรณี-พรณรงค์ กวีกาณ',
    branch_type: '-',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าขนส่งไม้',
  },
  {
    sup_code: 'S0127',
    sup_type: 'individual',
    sup_name: 'นางสาว ยุวาริณทร์ ติระโย',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างไม้',
  },
  {
    sup_code: 'S0126',
    sup_type: 'individual',
    sup_name: 'นาย ยงยศ ลิระการ',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างสี',
  },
  {
    sup_code: 'S0125',
    sup_type: 'company',
    sup_name: 'บริษัท วันนิยม จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ราง TOSO',
  },
  {
    sup_code: 'S0124',
    sup_type: 'individual',
    sup_name: 'นางสาว วิศัลยา ชัดียะ',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างสี',
  },
  {
    sup_code: 'S0123',
    sup_type: 'individual',
    sup_name: 'นาง ประภาพร วะสาร (ช่างมุ้ย)',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างติดตั้งผ้าม่าน',
  },
  {
    sup_code: 'S0122',
    sup_type: 'individual',
    sup_name: 'นาย ปลู่ว กานต์สุภพินิจ',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างไม้',
  },
  {
    sup_code: 'S0121',
    sup_type: 'individual',
    sup_name: 'นางสาว ชัชญา ภูริจิราธร',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างตัดเย็บผ้าม่าน',
  },
  {
    sup_code: 'S0120',
    sup_type: 'individual',
    sup_name: 'นาย คุณ จอ อู',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างสี',
  },
  {
    sup_code: 'S0119',
    sup_type: 'individual',
    sup_name: 'นางสาว ณัฐวิมณพรร ทองเทียนชัย',
    branch_type: '-',
    withholding_tax: '5',
    note: 'แนะนำงาน KNKR',
  },
  {
    sup_code: 'S0118',
    sup_type: 'individual',
    sup_name: 'นาย ภาณุพงศ์ สุขบัวใหญ่',
    branch_type: '-',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · ช่างวอลล์เปเปอร์',
  },
  {
    sup_code: 'S0117',
    sup_type: 'individual',
    sup_name: 'นางสาว เมธิยา แสงหิรัญ',
    branch_type: '-',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · ช่างสี',
  },
  {
    sup_code: 'S0116',
    sup_type: 'company',
    sup_name: 'ว่าง',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0115',
    sup_type: 'company',
    sup_name: 'ร้าน WHITE TOWELL',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'PILLOW',
  },
  {
    sup_code: 'S0114',
    sup_type: 'individual',
    sup_name: 'คม.ดีซายน์',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างตัดเย็บผ้าม่าน',
  },
  {
    sup_code: 'S0113',
    sup_type: 'individual',
    sup_name: 'นาย ชนก เดชมา',
    branch_type: '-',
    withholding_tax: '3',
    note: 'ช่างติดตั้งผ้าม่าน',
  },
  {
    sup_code: 'S0112',
    sup_type: 'company',
    sup_name: 'บริษัท วี.พี.ซี.กรุ๊ป จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'นั่งร้าน',
  },
  {
    sup_code: 'S0111',
    sup_type: 'company',
    sup_name: 'บริษัท วิชิน โกลบอล จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ROLLER',
  },
  {
    sup_code: 'S0110',
    sup_type: 'company',
    sup_name: 'บริษัท วีซี.แฟบริค จำกัด',
    branch_type: 'HO',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'CURTAIN · เครดิต 30วัน',
  },
  {
    sup_code: 'S0109',
    sup_type: 'company',
    sup_name: 'บริษัท ยูเทกซ์ไทล์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'Roller+ผ้าม่าน',
  },
  {
    sup_code: 'S0108',
    sup_type: 'company',
    sup_name: 'บริษัท ยูเทกษ์ สลิ้ฟวิ่ง สแตดาร์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'CURTAIN',
  },
  {
    sup_code: 'S0107',
    sup_type: 'company',
    sup_name: 'บริษัท เทกซ์ เวิลด์ ดีไซน์ อินเตอร์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'CURTAIN',
  },
  {
    sup_code: 'S0106',
    sup_type: 'company',
    sup_name: 'บริษัท ที แอนด์ ที ไบลนด์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน มู่ลี่ไม้',
  },
  {
    sup_code: 'S0105',
    sup_type: 'company',
    sup_name: 'บริษัท ธนธารา จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'งานสั่งตัดไม้ ทาสี',
  },
  {
    sup_code: 'S0104',
    sup_type: 'company',
    sup_name: 'บริษัท ทีวีจี ไทย จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0103',
    sup_type: 'company',
    sup_name: 'T I C GROUP CO.,LTD',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'หมึกพิมพ์',
  },
  {
    sup_code: 'S0102',
    sup_type: 'company',
    sup_name: 'บริษัท ไทยสง พลาสติก อินดัสทรี จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ถุงกันเลอะ',
  },
  {
    sup_code: 'S0101',
    sup_type: 'company',
    sup_name: 'บริษัท ทูโก โฮมโปรดักส์ จำกัด',
    branch_type: 'HO',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน · เครดิต',
  },
  {
    sup_code: 'S0100',
    sup_type: 'company',
    sup_name: 'บริษัท ทริพยสิน โฮมโปรดักส์ 2019 จำกัด',
    branch_type: 'HO',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน · เครดิต 30วัน',
  },
  {
    sup_code: 'S0099',
    sup_type: 'company',
    sup_name: 'บริษัท ซีซัน กรุ๊ป จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'โรงพิมพ์ BILL',
  },
  {
    sup_code: 'S0098',
    sup_type: 'company',
    sup_name: 'บริษัท เอสทีดี โพลีโปรดักส์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'บรรจุภัณฑ์',
  },
  {
    sup_code: 'S0097',
    sup_type: 'company',
    sup_name: 'บริษัท สมายล์ ดีไซน์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0096',
    sup_type: 'company',
    sup_name: 'บริษัท สยามไมโตรเวอร์คส์(1994) จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'รางม่าน',
  },
  {
    sup_code: 'S0095',
    sup_type: 'company',
    sup_name: 'บริษัท ซันลิฟ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ชัตเตอร์',
  },
  {
    sup_code: 'S0094',
    sup_type: 'company',
    sup_name: 'บริษัท ทรงกิจโฮมโปรดักส์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน มอร์เตอร์',
  },
  {
    sup_code: 'S0093',
    sup_type: 'company',
    sup_name: 'บริษัท สมายแฟบริค จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0092',
    sup_type: 'company',
    sup_name: 'บริษัท ซอมฟิ (ไทยแลนด์) จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'มอเตอร์',
  },
  {
    sup_code: 'S0091',
    sup_type: 'company',
    sup_name: 'บริษัท ศรีกรุงเซ็นเตอร์และบุตร จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน · ⚠️ tax placeholder',
  },
  {
    sup_code: 'S0090',
    sup_type: 'company',
    sup_name: 'บริษัท สยามไบลน์ จำกัด',
    branch_type: 'HO',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'มู่ลี่+ม่าน · เครดิต 30วัน',
  },
  {
    sup_code: 'S0089',
    sup_type: 'company',
    sup_name: 'บริษัท สตาร์บอร์ด ดีไซน์ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน',
  },
  {
    sup_code: 'S0088',
    sup_type: 'company',
    sup_name: 'บริษัท รอยัล ไทย อินเตอร์เนชั่นแนล จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'พรม',
  },
  {
    sup_code: 'S0087',
    sup_type: 'company',
    sup_name: 'บริษัท อาร์ดับบลิว วิลาวรรณ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'อุปกรณ์ม่าน',
  },
  {
    sup_code: 'S0086',
    sup_type: 'company',
    sup_name: 'บริษัท โรเบิร์ต บ๊อช จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'เลเซอร์',
  },
  {
    sup_code: 'S0085',
    sup_type: 'company',
    sup_name: 'บริษัท โปร เทคไทล โฮลเซล จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0084',
    sup_type: 'company',
    sup_name: 'บริษัท โปรมีนาค จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'รางผ้าม่าน',
  },
  {
    sup_code: 'S0083',
    sup_type: 'company',
    sup_name: 'ห้างหุ้นส่วนจำกัด ภัณฑ์ประเสริฐ ฮาร์ดแวร์',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'เทปม่านลอน',
  },
  {
    sup_code: 'S0082',
    sup_type: 'company',
    sup_name: 'บริษัท ฟีนิกซ์ อินเตอร์โฮม เทรดดิ้ง จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'อุปกรณ์ม่าน',
  },
  {
    sup_code: 'S0081',
    sup_type: 'company',
    sup_name: 'บริษัท เทกซ์ไทล์ แกลลอรี่ จำกัด',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0080',
    sup_type: 'company',
    sup_name: 'บริษัท ออฟฟิสเมท จำกัด (มหาชน)',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
    note: 'อุปกรณ์สำนักงาน',
  },
  {
    sup_code: 'S0079',
    sup_type: 'company',
    sup_name: 'บริษัท นิทัส เทสซีเล จำกัด',
    branch_type: 'HO',
    payment_term: 'เครดิต',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน · เครดิต 30วัน',
  },
  {
    sup_code: 'S0078',
    sup_type: 'company',
    sup_name: 'ธนาคารไทยพาณิชย์ จำกัด (มหาชน)',
    branch_type: 'HO',
    withholding_tax: 'ไม่หัก',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) { console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`); skipped++; continue; }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
