/**
 * Import suppliers S0231–S0250
 * node scripts/import_suppliers_s231_s250.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0250',
    sup_type: 'company',
    sup_name: 'บริษัท สโตน แกลเลอรี่ จำกัด',
    tax_id: '0105550002051',
    branch_type: 'HO',
    address_line1: '566 ถนนศรีนครินทร์ แขวงพัฒนาการ',
    sub_district: 'พัฒนาการ',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '02-720-4732-4',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ค่าหิน',
  },
  {
    sup_code: 'S0249',
    sup_type: 'individual',
    sup_name: 'นางสาวสายใหม่ สายแวว',
    tax_id: '3340100383621',
    branch_type: '-',
    address_line1: '55/474 ซ.เฉลิมพระเกียรติ ร.9 ซ.87',
    sub_district: 'ประเวศ',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'พี่อ้อ',
    contact_phone: '085-160-0930',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างบุ',
  },
  {
    sup_code: 'S0248',
    sup_type: 'individual',
    sup_name: 'นาย ประทุม จันใส',
    tax_id: '3540200279840',
    branch_type: '-',
    address_line1: '117 หมู่ที่ 2 ต.ไผ่โทน',
    district: 'ร้องกวาง',
    province: 'แพร่',
    postal_code: '54140',
    contact_name: 'ช่างไฟ',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างไฟ',
  },
  {
    sup_code: 'S0247',
    sup_type: 'individual',
    sup_name: 'นาย บดินทร์ กำเนิดเหมาะ',
    tax_id: '1101401547777',
    branch_type: '-',
    address_line1: '294/26 ถ.รามคำแหง',
    sub_district: 'หัวหมาก',
    district: 'บางกะปิ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10240',
    contact_name: 'คุณบาส',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างฟรีแลนซ์',
  },
  {
    sup_code: 'S0246',
    sup_type: 'individual',
    sup_name: 'นางสาว พิมพ์วรา รอดเรืองวงษ์',
    nickname: 'ช่างเงาะ',
    tax_id: '1103100003389',
    branch_type: '-',
    address_line1: '44 ซ.สุขสวัสดิ์ 26 แยก 6-1 แขวงบางประกอก',
    sub_district: 'บางประกอก',
    district: 'ราษฎร์บูรณะ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10140',
    contact_name: 'ช่างเงาะ',
    contact_phone: '088-942-9559',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างวอลล์เปเปอร์ · ม้วน 800 ฉาบแต่ง · ภาพเช็ค 1 ละ 1000 บาท',
  },
  {
    sup_code: 'S0245',
    sup_type: 'individual',
    sup_name: 'นางสาว อุสา หรมีฤทธิ์',
    tax_id: '3440600753388',
    branch_type: '-',
    address_line1: '43/1 หมู่ที่ 2 ต.กำพี้',
    district: 'บรบือ',
    province: 'มหาสารคาม',
    postal_code: '44130',
    contact_name: 'พี่อุสา',
    contact_phone: '061-463-6194',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ตลอดไป · ช่างเย็บผ้า',
  },
  {
    sup_code: 'S0244',
    sup_type: 'company',
    sup_name: 'ค่าใช้จ่าย บริษัท ลินสิลิน ลิฟวิ่ง จำกัด',
    branch_type: 'HO',
    address_line1: 'เลขที่ 99/73 ถ.เฉลิมพระเกียรติ ร.9',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_phone: '02-1620429',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าใช้จ่ายบริษัท',
  },
  {
    sup_code: 'S0243',
    sup_type: 'company',
    sup_name: 'บริษัท สยามอินเตอร์ไบลด์ จำกัด',
    tax_id: '0105565095637',
    branch_type: 'HO',
    address_line1: '1 ซอยนิมิตใหม่ 42 ถนนนิมิตใหม่ แขวงสามวาตะวันออก',
    sub_district: 'สามวาตะวันออก',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_phone: '096-264-0540',
    contact_phone2: '096-237-7186',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน',
  },
  {
    sup_code: 'S0242',
    sup_type: 'individual',
    sup_name: 'นาย สมโชค เสนประโคน',
    tax_id: '3310700349253',
    branch_type: '-',
    address_line1: '164 หมู่ที่ 7 ต.หนองบัวแก้ว',
    district: 'พยัคฆภูมิพิสัย',
    province: 'มหาสารคาม',
    postal_code: '44110',
    contact_name: 'ช่างโชค',
    contact_phone: '096-346-1387',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างไม้ (ช่างโชค)',
  },
  {
    sup_code: 'S0241',
    sup_type: 'company',
    sup_name: 'อีซีพาส/EASY PASS / ษณ 665',
    branch_type: 'HO',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าทางด่วน K.พิท ษณ 665',
  },
  {
    sup_code: 'S0240',
    sup_type: 'individual',
    sup_name: 'ว่าง',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0239',
    sup_type: 'company',
    sup_name: 'บริษัท ลินสิลิน ลิฟวิ่ง จำกัด 175',
    branch_type: 'HO',
    address_line1: 'เลขที่ 99/73 ถ.เฉลิมพระเกียรติ ร.9',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0238',
    sup_type: 'individual',
    sup_name: 'นาง ศิรินทร์ วงศ์วิวัฒน์',
    nickname: 'คุณก้อง',
    tax_id: '3100904473876',
    branch_type: '-',
    address_line1: '1695 ถ.อ่อนนุช แขวงอ่อนนุช',
    sub_district: 'อ่อนนุช',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณก้อง',
    contact_phone: '089-140-1100',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '5',
    note: 'ค่าคอมมิชชัน 5% · ผู้แนะนำโครงการ',
  },
  {
    sup_code: 'S0237',
    sup_type: 'company',
    sup_name: 'บริษัท ทริปเปิล เอ ไบแลนด์ จำกัด',
    tax_id: '0115566006263',
    branch_type: 'HO',
    address_line1: '140/12 หมู่ที่ 12 ตำบลราชาเทวะ',
    sub_district: 'ราชาเทวะ',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'วรกานต์ สักดิ์ศรีชมพู',
    contact_phone: '02-550-6655',
    contact_phone2: '081-254-2966',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0236',
    sup_type: 'individual',
    sup_name: 'นาย ขนรุจ ใบยา',
    nickname: 'คุณเดน',
    tax_id: '3550600003710',
    branch_type: '-',
    address_line1: '764/421 มน.วิสเตดไลท์ พัฒนาการ 38',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณเดน',
    contact_phone: '097-159-5492',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '5',
    note: 'ค่าคอมมิชชัน 5% · ผู้แนะนำโครงการ',
  },
  {
    sup_code: 'S0235',
    sup_type: 'company',
    sup_name: 'บริษัท ทูเดย์ สไลด์ 2100 จำกัด',
    tax_id: '0105543012119',
    branch_type: 'HO',
    address_line1: '1839 ถนนอ่อนนุช แขวงอ่อนนุช',
    sub_district: 'อ่อนนุช',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'ธัญรัตน์ ธรรมจีรพัฒน์',
    contact_phone: '+(66)2-118-3000',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'อุปกรณ์มือจับ ประตูหน้าต่าง Fitting',
  },
  {
    sup_code: 'S0234',
    sup_type: 'individual',
    sup_name: 'นาย คุน เยียง ฮาน',
    tax_id: '0010421165740',
    branch_type: '-',
    address_line1: '169/083 ซ.เพิ่มสิน 15 แยก 6',
    sub_district: 'คลองถนน',
    district: 'สายไหม',
    province: 'กรุงเทพมหานคร',
    postal_code: '10220',
    contact_name: 'ช่างอู',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างสี',
  },
  {
    sup_code: 'S0233',
    sup_type: 'company',
    sup_name: 'บริษัท มาเจสเทค เทรดดิ้ง (ประเทศไทย) จำกัด',
    tax_id: '0105555178785',
    branch_type: 'HO',
    address_line1: '2994 ชั้น 2 อิ้ลแพทท์โอ ถนนพัฒนาการ',
    sub_district: 'สวนหลวง',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณธัญชนก อำไพเรือนศักดิ์',
    contact_phone: '02-322-6094-5',
    contact_phone2: '082-541-2554',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'มุ้งมัจฉา',
  },
  {
    sup_code: 'S0232',
    sup_type: 'company',
    sup_name: 'บริษัท ดับเบิลวี เทรดดิ้ง อินเตอร์กรุ๊ป จำกัด',
    tax_id: '0105561165363',
    branch_type: 'HO',
    address_line1: '117 ซ.เจริญพัฒนาการ 11 แขวงบางชัน',
    sub_district: 'บางชัน',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_name: 'คุณพิทักษ์ อะราดี',
    contact_phone: '089-799-3189',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ฉากกั้นห้อง มู่ลี่ไม้ ม่านม้วน',
  },
  {
    sup_code: 'S0231',
    sup_type: 'individual',
    sup_name: 'นาย สุรสิทธิ์ นันธีสา',
    tax_id: '3310701121001',
    branch_type: '-',
    address_line1: '169 หมู่ที่ 7 ต.สำโรง',
    district: 'พลับพลาชัย',
    province: 'บุรีรัมย์',
    postal_code: '31250',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างไม้ (ช่างนะ)',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) {
      console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`);
      skipped++;
      continue;
    }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
