/**
 * Import suppliers S0251–S0270
 * node scripts/import_suppliers_s251_s270.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0270',
    sup_type: 'individual',
    sup_name: 'น.ส. ศิภัสร์ วิสุโท (แอน)',
    tax_id: '3750300397877',
    branch_type: '-',
    address_line1: '22 หมู่ 3 ต.วัดประดู่',
    district: 'อัมพวา',
    province: 'สมุทรสงคราม',
    contact_name: 'น.ส. ศิภัสร์ วิสุโท (แอน)',
    contact_phone: '0947193515',
    contact_phone2: '0957416130',
    payment_term: 'เงินสด',
    withholding_tax: '3',
    note: '3% ออกให้ตลอดไป',
  },
  {
    sup_code: 'S0269',
    sup_type: 'individual',
    sup_name: 'ว่าง',
    branch_type: '-',
    address_line1: '247 หมู่บ้านพฤกษ์',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0268',
    sup_type: 'company',
    sup_name: 'ห้างหุ้นส่วนจำกัด ชัยพฤกษ์ เดคคอร์ เซ็นเตอร์',
    tax_id: '0103556007745',
    branch_type: 'HO',
    address_line1: '255/10 ซอยองครักษ์ 9 ถนนสามเสน',
    sub_district: 'ถนนนครไชยศรี',
    district: 'ดุสิต',
    province: 'กรุงเทพมหานคร',
    contact_name: 'คุณตั้ง',
    contact_phone: '086-305-8341',
    contact_phone2: '02-403-1638',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '02-403-1639 · มีสาขาที่พัทยา',
  },
  {
    sup_code: 'S0267',
    sup_type: 'individual',
    sup_name: 'นางสาวพัทร์ศรัณย์ เกิดสมบูรณ์',
    tax_id: '3720700178587',
    branch_type: '-',
    address_line1: '118/9 หมู่ที่ 20 ต.บางพลีใหญ่',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'พี่อ้อ',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0266',
    sup_type: 'company',
    sup_name: 'บริษัท เอสเอ็มแอล พาเนล จำกัด',
    branch_type: 'HO',
    address_line1: '88 ซอยหนองระแหง แขวงสามวาตะวันตก',
    sub_district: 'สามวาตะวันตก',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_phone: '080-341-9904',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ไม่ HMR',
  },
  {
    sup_code: 'S0265',
    sup_type: 'company',
    sup_name: 'บริษัท ทะเลันโปรดักชั่น จำกัด',
    tax_id: '0115556018366',
    branch_type: 'HO',
    address_line1: '39/250 หมู่ 11 ต.บางแก้ว',
    sub_district: 'บางแก้ว',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'คุณเอเล็กซ์',
    contact_phone: '02-7387849',
    contact_phone2: '0816146827',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'โอนคืนยอดหัก 3% ลูกค้าคุณพิท',
  },
  {
    sup_code: 'S0264',
    sup_type: 'individual',
    sup_name: 'นางสาว เกวลิน มะรังษี',
    tax_id: '5450400052587',
    branch_type: '-',
    address_line1: '53/1 หมู่ที่ 15 ต.หัวข้าว',
    district: 'จตุรพักตรพิมาน',
    province: 'ร้อยเอ็ด',
    postal_code: '45180',
    contact_name: 'เกวลิน',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · รถรับจ้าง (ขนของ)',
  },
  {
    sup_code: 'S0263',
    sup_type: 'individual',
    sup_name: 'นายอนันทพงศ์ นวนประโคน',
    tax_id: '3310700350758',
    branch_type: '-',
    address_line1: '16 หมู่ที่ 9 ต.สำโรง',
    district: 'พลับพลาชัย',
    province: 'บุรีรัมย์',
    postal_code: '31250',
    contact_name: 'ช่างปอง',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างไม้ (ช่างปอง)',
  },
  {
    sup_code: 'S0262',
    sup_type: 'individual',
    sup_name: 'นายเรนส์ เจริญพรนิมิต',
    tax_id: '8571084037018',
    branch_type: '-',
    address_line1: '185 หมู่ที่ 20 ต.วาวี',
    district: 'แม่สรวย',
    province: 'เชียงราย',
    postal_code: '57180',
    contact_name: 'ช่างนนท์',
    contact_phone: '091-794-1681',
    contact_phone2: '0904751099',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างวอลล์เปเปอร์ **ช่างไม่มีนิ้วร้าน**',
  },
  {
    sup_code: 'S0261',
    sup_type: 'individual',
    sup_name: 'นายสิทธิโชค สุระดโก',
    branch_type: '-',
    contact_name: 'คุณสิท',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'โอนคืนยอดหัก 3% ลูกค้าคุณพิท',
  },
  {
    sup_code: 'S0260',
    sup_type: 'company',
    sup_name: 'สำนักงานเขตประเวศ',
    branch_type: 'HO',
    address_line1: '33 ถนนเฉลิมพระเกียรติ ร.9 ซอย 81 ต.เฉลิมพระเกียรติ',
    sub_district: 'ประเวศ',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'เพื่อนพี่บาส',
    contact_phone: '082-449-8388',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'รถดูดส้วมออฟฟิส (1 ลบม. = 250 บาท)',
  },
  {
    sup_code: 'S0259',
    sup_type: 'company',
    sup_name: 'บริษัท วิรัยประกันภัย จำกัด (มหาชน)',
    tax_id: '0107555000139',
    branch_type: 'HO',
    address_line1: '121/28, 121/65 อาร์เอส ทาวเวอร์ ถนนรัชดาภิเษก',
    sub_district: 'ดินแดง',
    district: 'ดินแดง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10400',
    contact_name: 'คุณมัลลิกา วงค์จำปา',
    contact_phone: '02-633-6089',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: 'ประกันสินเชื่อรถ CX-5 ค่าเบี้ยประกันและค่า พ.ร.บ.',
  },
  {
    sup_code: 'S0258',
    sup_type: 'individual',
    sup_name: 'นายรุ่ง เถาวัลยา',
    tax_id: '3560300596278',
    branch_type: '-',
    address_line1: '99 หมู่ที่ 1 ต.ฝ่ายกวาง',
    district: 'เขียงคำ',
    province: 'พะเยา',
    postal_code: '56110',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · ค่าขนขยะโรงงาน',
  },
  {
    sup_code: 'S0257',
    sup_type: 'individual',
    sup_name: 'นางสาววาสนา ผู้จำรูญ',
    tax_id: '3361300321590',
    branch_type: '-',
    address_line1: '3 หมู่ที่ 4 ต.ห้วยยาง',
    district: 'คอนสาร',
    province: 'ชัยภูมิ',
    postal_code: '36180',
    contact_name: 'พี่วาส',
    contact_phone: '087-409-9404',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'แม่บ้าน',
  },
  {
    sup_code: 'S0256',
    sup_type: 'individual',
    sup_name: 'นายอนุสรณ์ พยัคษภาพ',
    tax_id: '3650500463394',
    branch_type: '-',
    address_line1: '39/3 หมู่ที่ 3 ต.บ้านไร่',
    district: 'บางกระทุ่ม',
    province: 'พิษณุโลก',
    postal_code: '65110',
    contact_name: 'ช่างหมู',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'ช่างไม้ (ช่างหมู)',
  },
  {
    sup_code: 'S0255',
    sup_type: 'individual',
    sup_name: 'นายส่งสุข จิตร์มีทรัพย์',
    branch_type: '-',
    address_line1: '220 ซ.ประชานฤมิตร(24) ถ.ประชาราษฎร์ 1',
    sub_district: 'บางซื่อ',
    district: 'บางซื่อ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10800',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ร้านไม้ ส.จิตการช่าง',
  },
  {
    sup_code: 'S0254',
    sup_type: 'individual',
    sup_name: 'นายจิรายุพันธ์ อยู่เป็นสุข',
    tax_id: '1102700156576',
    branch_type: '-',
    address_line1: '6/58 หมู่ที่ 6 แขวงราชาเทวะ',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'พี่โอ้',
    contact_phone: '0922574155',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
    note: '4 ก.พ.2535',
  },
  {
    sup_code: 'S0253',
    sup_type: 'individual',
    sup_name: 'นางสาว จารุวรรณ แซ่ชิ้ง',
    tax_id: '1129900082939',
    branch_type: '-',
    address_line1: '93/6 หมู่ที่ 2 ต.พิมลราช',
    district: 'บางบัวทอง',
    province: 'นนทบุรี',
    postal_code: '11110',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว · ค่าทำความสะอาดบ้านคุณโม',
  },
  {
    sup_code: 'S0252',
    sup_type: 'company',
    sup_name: 'สำนักงานประกันสังคม กรุงเทพมหานครพื้นที่8',
    branch_type: 'HO',
    address_line1: 'ศูนย์การค้าญาณาพาร์ค อาคาร D ชั้น 1 เลขที่ 735/4 ถนนศรีนครินทร์',
    sub_district: 'พัฒนาการ',
    district: 'สวนหลวง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    payment_term: 'เงินสด',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0251',
    sup_type: 'company',
    sup_name: 'บริษัท เอคิว พร้อพเพอร์ตี้ แมเนจเม้นท์ จำกัด',
    tax_id: '0105539039083',
    branch_type: 'HO',
    address_line1: '102 ถนนมิตรไมตรี แขวงบางกะปิ',
    sub_district: 'บางกะปิ',
    district: 'ห้วยขวาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'AQ ARBOR',
    contact_phone: '090-960-0716',
    contact_phone2: '085-487-4719',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) {
      console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`);
      skipped++;
      continue;
    }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
