/**
 * Import suppliers S0292–S0311
 * node scripts/import_suppliers_s292_s311.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0311',
    sup_type: 'individual',
    sup_name: 'คุณวิเชียร อมรตระกูล',
    tax_id: '4101400006025',
    branch_type: '-',
    address_line1: '74/1 ซอยเฉลิมพระเกียรติ ร.9 ซ.33 ถนนสุขุมวิท 103',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'คุณแอ้ย',
    contact_phone: '087-7171420',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    partner_type: 'อุปกรณ์ และ รางผ้าม่าน',
  },
  {
    sup_code: 'S0310',
    sup_type: 'individual',
    sup_name: 'นางสาว นันทรัตน์ มาลาลักษมี',
    tax_id: '3102102126777',
    branch_type: '-',
    address_line1: '29/26 ซอยอินทามระ 26',
    sub_district: 'รัชดาภิเษก',
    district: 'ดินแดง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10400',
    contact_name: 'คุณสเมธ',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'บัตรประชาชนที่สาวคุณสเมธ',
  },
  {
    sup_code: 'S0309',
    sup_type: 'company',
    sup_name: 'บริษัท วนขัย รู้ดสมิธ จำกัด',
    tax_id: '0105560161275',
    branch_type: 'HO',
    address_line1: '2/1 ถนนวงศ์สว่าง',
    sub_district: 'วงศ์สว่าง',
    district: 'บางซื่อ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10800',
    contact_name: 'คุณยัน',
    contact_phone: '083-820-5734',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0308',
    sup_type: 'individual',
    sup_name: 'นายเอกศักดิ์ ภาสี',
    tax_id: '1539900012767',
    branch_type: '-',
    address_line1: '155 หมู่ 10 ต.สำโรงเหนือ',
    district: 'เมืองสมุทรปราการ',
    province: 'สมุทรปราการ',
    postal_code: '10270',
    contact_name: 'คุณโอ',
    contact_phone: '096-090-9665',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: '3% ออกให้ครั้งเดียว',
  },
  {
    sup_code: 'S0307',
    sup_type: 'company',
    sup_name: 'บริษัท ตั้งอ่งหลี จำกัด',
    tax_id: '0105518000315',
    branch_type: 'HO',
    address_line1: '354 ถนนพาหุรัด',
    sub_district: 'วังบูรพาภิรมย์',
    district: 'พระนคร',
    province: 'กรุงเทพมหานคร',
    postal_code: '10200',
    contact_phone: '02-221-8709',
    contact_phone2: '02-623-7053',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0306',
    sup_type: 'company',
    sup_name: 'บริษัท พีเอลที เดคอร์ จำกัด',
    tax_id: '0115567022092',
    branch_type: 'HO',
    address_line1: 'เลขที่ 50/243 หมู่ที่ 14 ตำบลบางแก้ว',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'คุณริต้า',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0305',
    sup_type: 'company',
    sup_name: 'บริษัท ลัดซุรี เวิลด์ จำกัด',
    tax_id: '0105554126901',
    branch_type: 'BR',
    branch_no: '00001',
    address_line1: '2/4 ซอยกรุงเทพกรีฑา 21',
    sub_district: 'สะพานสูง',
    district: 'สะพานสูง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10240',
    contact_name: 'คุณเปิ้ก',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'วางบิล / รับเช็ค',
  },
  {
    sup_code: 'S0304',
    sup_type: 'individual',
    sup_name: 'คุณภาคภูมิ หอมสุวรรณ',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0303',
    sup_type: 'individual',
    sup_name: 'บริษัท ทิพพอท จำกัด',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0302',
    sup_type: 'company',
    sup_name: 'บริษัท แอ็ดส์ บีช สโตน แอนด์ เดคคอร์ จำกัด',
    tax_id: '0105550010657',
    branch_type: 'HO',
    address_line1: '25 ซอยรามอินทรา 5 แยก 9',
    sub_district: 'อนุสาวรีย์',
    district: 'บางเขน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10220',
    contact_phone: '02-5514435',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'NO VAT เลขบัญชี 881-200-7999 กสิกรไทย',
  },
  {
    sup_code: 'S0301',
    sup_type: 'individual',
    sup_name: 'คุณประภาส เนรเพ็ชร',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0300',
    sup_type: 'individual',
    sup_name: 'อภิชาติ วงศ์ประเสริฐกุล',
    branch_type: '-',
    contact_phone: '089-1158889',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ค่าหนี้ บ.แอ็ดส์ บีช สโตน แอนด์ เดคคอร์ จำกัด ฝ่ายขายคือ อภิชาติ วงศ์ประเสริฐกุล',
  },
  {
    sup_code: 'S0299',
    sup_type: 'individual',
    sup_name: 'นายมานิตย์ สุขคุ้ม',
    tax_id: '3660800333135',
    branch_type: '-',
    address_line1: '520 หมู่ที่ 4 ต.ทับคล้อ',
    district: 'ทับคล้อ',
    province: 'พิจิตร',
    postal_code: '66150',
    contact_name: 'ช่างโสภา',
    contact_phone: '090-991-8619',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0298',
    sup_type: 'company',
    sup_name: 'บริษัท โปร เวิร์ค รีเทล จำกัด',
    tax_id: '0905551001816',
    branch_type: 'BR',
    branch_no: '00004',
    address_line1: 'เลขที่ 2 ซอยบางบอน 4 ซอย 8 ถนน-แขวงบางบอน',
    district: 'บางบอน',
    province: 'กรุงเทพมหานคร',
    postal_code: '10150',
    contact_phone: '064-623-6462',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    partner_type: 'จำนายไฟฟ้า',
  },
  {
    sup_code: 'S0297',
    sup_type: 'individual',
    sup_name: 'นายอาทิตย์ ทองบุญ',
    tax_id: '3190800109337',
    branch_type: '-',
    address_line1: '434 ซอยรามคำแหง39(เทพลีลา1)',
    sub_district: 'พลับพลา',
    district: 'วังทองหลาง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10310',
    contact_name: 'คุณต้น',
    contact_phone: '081-269-0941',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
    note: 'คุณต้นรถดู',
  },
  {
    sup_code: 'S0296',
    sup_type: 'company',
    sup_name: 'บริษัท โฮมกลาส 2033 จำกัด',
    tax_id: '0105546109261',
    branch_type: 'HO',
    address_line1: '645, 647, 649 ถนนรามอินทรา',
    sub_district: 'คันนายาว',
    district: 'คันนายาว',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_name: 'คุณหนิง',
    contact_phone: '094-4272-229',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    partner_type: 'จำนายกระจก',
  },
  {
    sup_code: 'S0295',
    sup_type: 'individual',
    sup_name: 'บริษัท ไฟว์สตาร์แมชชินทูล จำกัด',
    tax_id: '0105534027818',
    branch_type: '-',
    address_line1: '330/1 ถนนมหาจักร',
    sub_district: 'ป้อมปราบ',
    district: 'ป้อมปราบศัตรูพ่าย',
    province: 'กรุงเทพมหานคร',
    postal_code: '10100',
    contact_phone: '02-222-3720',
    contact_phone2: '02-2259017',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0294',
    sup_type: 'individual',
    sup_name: 'นภัทร หงษ์จันทร์',
    tax_id: '3120101116008',
    branch_type: '-',
    address_line1: '202 ซอยรัชนาธิเบศร์ 18 ต.บางกระสอ',
    district: 'เมืองนนทบุรี',
    province: 'นนทบุรี',
    postal_code: '11000',
    contact_name: 'คุณจอย',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: '3',
  },
  {
    sup_code: 'S0293',
    sup_type: 'individual',
    sup_name: 'พัชยา เกษมสุขสถาพร',
    branch_type: '-',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
  },
  {
    sup_code: 'S0292',
    sup_type: 'company',
    sup_name: 'บริษัท เอ็น.เด. 2006 จำกัด',
    tax_id: '0105549062347',
    branch_type: 'HO',
    address_line1: 'เลขที่ 1/1, 1/2 ซอยพาณิชยการธนบุรี 21 แยก 3-1 ถนนจรัญสนิทวงศ์',
    sub_district: 'วัดท่าพระ',
    district: 'บางกอกใหญ่',
    province: 'กรุงเทพมหานคร',
    postal_code: '10600',
    contact_name: 'คุณวิภู',
    contact_phone: '06-4146-4536',
    contact_phone2: '02-864-2323',
    payment_term: 'เงินสด / เงินโอน',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าโพรน 1 ม้วน 60หลา / หลาละ 26 บาท',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null, status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;

  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) {
      console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`);
      skipped++;
      continue;
    }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }

  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
