/**
 * Import suppliers S0001–S0017
 * node scripts/import_suppliers_s001_s017.js
 */
const knexConfig = require('../knexfile.js');
const knex = require('knex')(knexConfig.development);

const rows = [
  {
    sup_code: 'S0017',
    sup_type: 'company',
    sup_name: 'บริษัท เดคคอร์ อาร์ด แฟบริค จำกัด (ยกเล็ก)',
    branch_type: 'HO',
    address_line1: '119/599 ถ.นวมินทร์ แขวงคลองกุ่ม',
    sub_district: 'คลองกุ่ม',
    district: 'บึงกุ่ม',
    province: 'กรุงเทพมหานคร',
    postal_code: '10230',
    contact_name: 'Sales.คุณสมชาย อมรชาครกิจ (แก้ว)',
    contact_phone: '085-812-9757',
    contact_phone2: 'T.02-948-4592 F.02-948-6069',
    withholding_tax: 'ไม่หัก',
    note: 'มู่ลี่ไม้',
  },
  {
    sup_code: 'S0016',
    sup_type: 'company',
    sup_name: 'บริษัท ค็อดเท็กซ์ จำกัด',
    branch_type: 'HO',
    tax_id: '0105549030348',
    address_line1: '52/21 soi.Prachautit 72 Prachautit Rd.',
    district: 'ทุ่งครุ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10140',
    contact_name: 'Sales.คุณสมชาย อมรชาครกิจ (แก้ว)',
    contact_phone: '085-812-9757',
    contact_phone2: 'T.02-871-8641 F.02-871-9801',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0015',
    sup_type: 'company',
    sup_name: 'บริษัท ชิตีมา (1992) จำกัด',
    branch_type: 'HO',
    address_line1: '998 ถนนลาซาล แขวงบางนา เขตบางนา',
    sub_district: 'บางนา',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'Sales.คุณกัลยาณี จีนบุญมี นก',
    contact_phone: '094-989-9589',
    contact_phone2: 'T.02-349-4651-3 F.02-710-5711',
    contact_email: 'www.chitima.co.th',
    withholding_tax: 'ไม่หัก',
    note: 'วอลล์เปเปอร์',
  },
  {
    sup_code: 'S0014',
    sup_type: 'company',
    sup_name: 'บริษัท เจริญเดคคอร์ อินเตอร์แนชั่นแนล จำกัด',
    branch_type: 'HO',
    address_line1: '300 Soi Ekamai 16, Sukhumvit 63',
    sub_district: 'คลองตันเหนือ',
    district: 'วัฒนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10110',
    contact_name: 'Sales.คุณวราพร รอดไพบูลย์',
    contact_phone: '089-518-3010',
    contact_phone2: 'T.02-381-8388 F.02-381-8398',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0013',
    sup_type: 'company',
    sup_name: 'บริษัท ชาลียา จำกัด',
    branch_type: 'HO',
    tax_id: '0105551053449',
    address_line1: '18/89 ซอยนวมินทร์ 111 แยก 15 ถนนนวมินทร์',
    sub_district: 'นวมินทร์',
    district: 'บึงกุ่ม',
    province: 'กรุงเทพมหานคร',
    postal_code: '10240',
    contact_name: 'Sales.คุณมุ้ย',
    contact_phone: '061-413-2992',
    contact_phone2: 'T.02-211-3009',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน (ที่อยู่อัพเทพ 07/67) / เซลส์อัพเดต 01/69',
  },
  {
    sup_code: 'S0012',
    sup_type: 'company',
    sup_name: 'บริษัท แคปิตอล คาร์เพท จำกัด (ยกเลิกใช้ S0197 แทน)',
    branch_type: 'HO',
    address_line1: 'เลขที่ 32 ซอยอุดมสุข31 ถนนสุขุมวิท103 แขวงบางจาก',
    sub_district: 'บางจาก',
    district: 'พระโขนง',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'ชีด้า มีประทัง',
    contact_phone: '086-016-7832',
    contact_phone2: 'T.02-383-8850 F.02-383-8860',
    withholding_tax: 'ไม่หัก',
    note: 'พรม',
  },
  {
    sup_code: 'S0011',
    sup_type: 'company',
    sup_name: 'โรงงานทอผ้าบีด้า',
    branch_type: 'HO',
    tax_id: '0115535007721',
    address_line1: '53/3-7 หมู่ 5 ถ.เทพารักษ์ ต.บางพลีใหญ่',
    sub_district: 'บางพลีใหญ่',
    district: 'บางพลี',
    province: 'สมุทรปราการ',
    postal_code: '10540',
    contact_name: 'Sales.คุณเอกสิทธิ์ ศรีชวาลา',
    contact_phone: '081-347-0912',
    contact_phone2: '081-347-0907',
    withholding_tax: 'ไม่หัก',
    note: 'ทอผ้า · T.02-385-5090-1',
  },
  {
    sup_code: 'S0010',
    sup_type: 'company',
    sup_name: 'บริษัท บี.ดับบลิว.พี.จำกัด B.W.P. CO.,LTD.',
    branch_type: 'HO',
    address_line1: '119/47 หมู่ 8 ถนนบางนา-ตราด',
    sub_district: 'บางนา',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'Sales.คุณสมชาย',
    contact_phone: '087-022-7315',
    contact_phone2: 'T.02-746-8887 F.02-746-9893',
    payment_term: 'วางบิล / รับเช็ค',
    withholding_tax: 'ไม่หัก',
    note: 'วอลล์เปเปอร์',
  },
  {
    sup_code: 'S0009',
    sup_type: 'company',
    sup_name: 'บริษัท บางกอกวอลล์เปเปอร์ จำกัด',
    branch_type: 'HO',
    tax_id: '0105531065301',
    address_line1: '21 ซอยบางนา-ตราด34 แขวงบางนาใต้',
    sub_district: 'บางนาใต้',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'Sales.คุณสมชาย สุขสม',
    contact_phone: '087-022-7215',
    contact_phone2: 'T.02-746-8887 F.02-746-8800',
    withholding_tax: 'ไม่หัก',
    note: 'วอลล์เปเปอร์',
  },
  {
    sup_code: 'S0008',
    sup_type: 'company',
    sup_name: 'บริษัท โพธิ์ ทรี เดคคอร์ จำกัด',
    branch_type: 'HO',
    address_line1: 'เลขที่ 55 ซอยอุดมสุข 51',
    district: 'บางนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10260',
    contact_name: 'Sales.ภาณุพงส์ (กอล์ฟ)',
    contact_phone: '092-283-3495',
    contact_phone2: 'T.02-746-5465 F.02-747-9433',
    contact_email: 'www.bodhitree.co.th',
    withholding_tax: 'ไม่หัก',
    note: 'วอลล์เปเปอร์ เข็ด',
  },
  {
    sup_code: 'S0007',
    sup_type: 'company',
    sup_name: 'บริษัท บีไอดับบลิว โปรดักส์ จำกัด',
    branch_type: 'HO',
    address_line1: 'เลขที่ 220/72 ถ.ปัญญาอินทรา แขวงบางชัน',
    sub_district: 'บางชัน',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_name: 'Sales.คุณสเมิงยริติ พรหมมา',
    contact_phone: '094-961-0098',
    contact_phone2: 'T.02-548-0562 F.02-548-0563',
    payment_term: 'วางบิล / รับเช็ค',
    credit_day: 30,
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน',
  },
  {
    sup_code: 'S0006',
    sup_type: 'company',
    sup_name: 'บริษัท อาควา-เทค อินเตอร์เนชั่นแนล จำกัด',
    branch_type: 'HO',
    tax_id: '0105547050309',
    address_line1: 'ชั้น 8 อาคารบีบี บิลดิ้ง 54 ถนนสุขุมวิท 21 แขวงคลองเตยเหนือ',
    sub_district: 'คลองเตยเหนือ',
    district: 'วัฒนา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10110',
    contact_name: 'Sales.คุณกรานติรัตน์ ดวรฝุ่ง',
    contact_phone2: 'T.02-261-0057-8 F.02-261-0059',
    withholding_tax: 'ไม่หัก',
    note: 'คู่ค้า',
  },
  {
    sup_code: 'S0005',
    sup_type: 'company',
    sup_name: 'บริษัท เอ แอนด์ ที แท็กซ์ไทล์ (ประเทศไทย) จำกัด (ชื่อบัญชี น.ส.อำพร แซ่ลี้)',
    branch_type: 'HO',
    tax_id: '0105558118198',
    address_line1: 'เลขที่ 75 ซอยหทัยราษฎร์ 37 แขวงสามวาตะวันตก',
    sub_district: 'สามวาตะวันตก',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_phone: '085-389-6623',
    contact_phone2: 'T.083-561-6688 F.02-136-0948',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0004',
    sup_type: 'company',
    sup_name: 'บริษัท อาร์ค โปรดักส์ จำกัด',
    branch_type: 'HO',
    tax_id: '0105544053455',
    address_line1: 'เลขที่ 6 ซ.พุทธบูชา 41 ถ.พุทธบูชา',
    sub_district: 'บางมด',
    district: 'ทุ่งครุ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10140',
    contact_name: 'Sales.คุณก้อ',
    contact_phone: '081-833-4593',
    contact_phone2: '094-483-9899',
    withholding_tax: 'ไม่หัก',
    note: 'ม่านม้วน · T.02-426-5301-4 F.02-426-5300',
  },
  {
    sup_code: 'S0003',
    sup_type: 'company',
    sup_name: 'บริษัท เอเซีย แฟบริค พลัส จำกัด',
    branch_type: 'HO',
    tax_id: '0105562093048',
    address_line1: 'เลขที่ 73 ซ.หทัยราษฎร์ 37 แขวงสามวาตะวันตก',
    sub_district: 'สามวาตะวันตก',
    district: 'คลองสามวา',
    province: 'กรุงเทพมหานคร',
    postal_code: '10510',
    contact_name: 'Sales.คุณเนพล (คุณเม)',
    contact_phone: '083-081-8125',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0002',
    sup_type: 'company',
    sup_name: 'บริษัท อาเคเซียแฟบริคส์ (ประเทศไทย) จำกัด',
    branch_type: 'HO',
    tax_id: '0105549092700',
    address_line1: 'เลขที่ 22 ซ.ศรีนครินทร์ 56 ถ.ศรีนครินทร์',
    sub_district: 'หนองบอน',
    district: 'ประเวศ',
    province: 'กรุงเทพมหานคร',
    postal_code: '10250',
    contact_name: 'Sales.คุณสวรรณา (คุณจิ๊บ)',
    contact_phone: '086-981-9988',
    contact_phone2: 'T.02-059-4410',
    payment_term: 'วางบิล / รับเช็ค',
    withholding_tax: 'ไม่หัก',
    note: 'ผ้าม่าน',
  },
  {
    sup_code: 'S0001',
    sup_type: 'individual',
    sup_name: 'นาย อรรถ ประพันธ์วัฒนะ',
    branch_type: '-',
    tax_id: '3249900171864',
    address_line1: 'เลขที่ 142 ถ.วรรณยิ่ง ต.หน้าเมือง',
    sub_district: 'หน้าเมือง',
    district: 'เมืองฉะเชิงเทรา',
    province: 'ฉะเชิงเทรา',
    postal_code: '24000',
    contact_name: 'คุณอรรถ',
    contact_phone: '083-908-2848',
    withholding_tax: '5',
    note: 'คอมมิชชั่น',
  },
];

const defaults = {
  nickname: null, tax_id: null, category: '', partner_type: null, branch_no: null,
  sub_district: null, district: null, province: null, postal_code: null,
  address_line1: null, contact_name: null, contact_phone: null,
  contact_phone2: null, contact_email: null, credit_day: 0, note: null,
  payment_term: 'เงินสด / เงินโอน', status: 'active',
};

async function run() {
  let inserted = 0, skipped = 0;
  for (const row of rows) {
    const existing = await knex('suppliers').where('sup_code', row.sup_code).first();
    if (existing) { console.log(`  [SKIP]   ${row.sup_code} มีอยู่แล้ว`); skipped++; continue; }
    await knex('suppliers').insert({ ...defaults, ...row });
    console.log(`  [INSERT] ${row.sup_code} ${row.sup_name}`);
    inserted++;
  }
  const total = await knex('suppliers').whereNull('deleted_at').count('id as n').first();
  console.log(`\nเสร็จสิ้น: INSERT ${inserted} | SKIP ${skipped}`);
  console.log(`รวมในระบบ: ${total.n} รายการ`);
  await knex.destroy();
}

run().catch(e => { console.error(e.message); process.exit(1); });
